### ISSUE TITLE
Attempting to "import originals" times out

### ISSUE THREAD

**Issue by JRGould** [GlotPress/GlotPress#1]
Tried a few times to import the WPMDB .mo file, but keep getting timeouts:

``` php
[28-Aug-2015 23:55:46 UTC] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /.../glotpress/gp-includes/strings.php on line 58
[28-Aug-2015 23:55:46 UTC] PHP Stack trace:
[28-Aug-2015 23:55:46 UTC] PHP   1. {main}() /.../glotpress-plugin.dev/index.php:0
[28-Aug-2015 23:55:46 UTC] PHP   2. require() /.../glotpress-plugin.dev/index.php:17
[28-Aug-2015 23:55:46 UTC] PHP   3. require_once() /.../glotpress-plugin.dev/wp-blog-header.php:16
[28-Aug-2015 23:55:46 UTC] PHP   4. do_action() /.../glotpress-plugin.dev/wp-includes/template-loader.php:12
[28-Aug-2015 23:55:46 UTC] PHP   5. call_user_func_array:{/.../glotpress-plugin.dev/wp-includes/plugin.php:496}() /.../glotpress-plugin.dev/wp-includes/plugin.php:496
[28-Aug-2015 23:55:46 UTC] PHP   6. gp_run_route() /.../glotpress-plugin.dev/wp-includes/plugin.php:496
[28-Aug-2015 23:55:46 UTC] PHP   7. GP_Router->route() /.../glotpress/gp-settings.php:170
[28-Aug-2015 23:55:46 UTC] PHP   8. call_user_func_array:{/.../glotpress/gp-includes/router.php:168}() /.../glotpress/gp-includes/router.php:168
[28-Aug-2015 23:55:46 UTC] PHP   9. GP_Route_Project->import_originals_post() /.../glotpress/gp-includes/router.php:168
[28-Aug-2015 23:55:46 UTC] PHP  10. GP_Original->import_for_project() /.../glotpress/gp-includes/routes/project.php:115
[28-Aug-2015 23:55:46 UTC] PHP  11. GP_Original->closest_original() /.../glotpress/gp-includes/things/original.php:145
[28-Aug-2015 23:55:46 UTC] PHP  12. gp_string_similarity() /.../glotpress/gp-includes/things/original.php:226
[28-Aug-2015 23:55:46 UTC] PHP  13. gp_levenshtein() /.../glotpress/gp-includes/strings.php:98
[28-Aug-2015 23:55:46 UTC] PHP  14. gp_substr() /.../glotpress/gp-includes/strings.php:139

```

**Comment by gilbitron** [comment]
I get the same. Did some digging but came up empty. Not sure what is causing this.

**Comment by A5hleyRich** [comment]
I've spent a good chunk of time on this too but I'm unable to see what's causing the issue. The timeout occurs progressively after a few original strings have been added. I believe the issue lies around https://github.com/deliciousbrains/GlotPress/blob/wordpress-plugin-dbi/gp-includes/things/original.php#L145 and is possibly due to calling `gp_levenshtein` recursively:

**Comment by gilbitron** [comment]
> is possibly due to calling gp_levenshtein recursively

That's about as far as I got with my investigation as well.

**Comment by JRGould** [comment]
Dug a little deeper into this and discovered that importing was actually working fine, just notices weren't displaying. #25 

The issue occurs when re-importing the same po or mo file (because you couldn't tell that it imported the first time). In the standalone glotpress the entries are successfully identified as duplicates and then checked to see if they update the existing version:

![image](https://cloud.githubusercontent.com/assets/1509647/10210224/ff6b6a16-6798-11e5-9b29-0c73184041e0.png)

While in this version doesn't seem to recognize that and goes into the recursive similarity check which just times out because each call to gp_levenshtien takes about half a second and it's being called ( I believe) `n^n` times where `n` is the number of entries in the po/mo file. 

So while `import_for_project` could probably use some refactoring to allow it to batch calls to `closest_original`, I think the main issue here is that imported strings for some reason aren't being identified as direct duplicates of originals.

**Comment by JRGould** [comment]
I've figured out what's going wrong here. In `import_for_project` we're checking each of the uploaded translations to see if it already exists in the project by looping through the array and seeing if each key is a key in the existing set: https://github.com/deliciousbrains/GlotPress/blob/wordpress-plugin-dbi/gp-includes/things/original.php#L111 but none are found to be even when reimporting the same file.

I'm assuming that this has something to do with utf8mb4 encoding because the keys for translations pulled from db are encoded as utf8 and have a BOM character (or something like it) at the start of the string `ord(original_first_char)===4` where the imported translations' keys are encoded as ascii and don't have the BOM character. 

I haven't had time to figure out a solution yet, in my setup I could just save the `originals_by_key` key as `substr(original_key, 1)` if it's encoded as utf8, but that's probably not a complete solution. 

This has been a rabbit hole for me, so I won't be surprised if the ideal solution is obvious to someone else - please let me know or feel free to submit a PR, otherwise I'll dive back into this at a later date.

**Comment by ocean90** [comment]
Even with latin1 charset I get something odd:
When importing wordpress.pot I get the notice "1716 new strings added, 0 updated, 0 fuzzied, and 0 obsoleted.". Importing the same produces "55 new strings added, 177 updated, 1484 fuzzied, and 55 obsoleted.", but it should be "0 new strings added, 1716 updated, 0 fuzzied, and 0 obsoleted."

Related: It seems like I also can't import translations.

**Comment by toolstack** [comment]
The import translations issue is due to #52, $gpdb->insert() does some extra stuff around empty values that $wpdb->insert() doesn't do (maybe it did in the past?).

I wouldn't be surprised if the timeout thing is related to this as well.

**Comment by ocean90** [comment]
With the current trunk version of WordPress I can't reproduce the issues anymore.

@JRGould Which WordPress version are you using? Does it still happen with trunk?

**Comment by JRGould** [comment]
I've just tried this out on the latest nightly build and am still getting this error. @ocean90 were you trying to reimport the same set of originals or was this a first-time upload?

**Comment by ocean90** [comment]
@JRGould I also did a reimport.

My steps on a fresh install:
- Create a new project
- Import originals from https://i18n.trac.wordpress.org/browser/pot/trunk/wordpress.pot
- Notice: 1778 new strings added, 0 updated, 0 fuzzied, and 0 obsoleted.
- Import originals from https://i18n.trac.wordpress.org/browser/pot/trunk/wordpress.pot again
- Notice: 0 new strings added, 1778 updated, 0 fuzzied, and 0 obsoleted.
- Create a new translation set
- Import translations from https://i18n.trac.wordpress.org/browser/core/4.3/de_DE/de_DE.po
- Notice: 1654 translations were added
- Import translations from https://i18n.trac.wordpress.org/browser/core/4.3/de_DE/de_DE.po again
- Notice: 0 translations were added
- Import originals from https://i18n.trac.wordpress.org/browser/pot/trunk/wordpress.pot again
- 0 new strings added, 1778 updated, 0 fuzzied, and 0 obsoleted.

DB collation is utf8mb4_unicode_ci.

**Comment by JRGould** [comment]
Ah, looks like this is only happening for .mo files

**Comment by ocean90** [comment]
I just tried the same with de_DE.mo from http://downloads.wordpress.org/translation/core/4.3.1/de_DE.zip

First import: 1716 new strings added, 0 updated, 0 fuzzied, and 0 obsoleted.
Second import: 0 new strings added, 1716 updated, 0 fuzzied, and 0 obsoleted.

**Comment by JRGould** [comment]
Interesting.

You're right, @ocean90. Looks like this is fixed on the 4.4 nightly, but the fix isn't backwards compatible. I've tested with .pot and .mo files and if you create a new project and upload originals in 4.3.x, then upgrade wp to a 4.4 build  and try to upload the same set of originals, the timeout occurs. If you are already running 4.4 and create a new project, upload originals then re-upload of the same works fine.

If I had to venture a guess it'd be that something's changed with the way WP is storing text that it no longer saves the BOM with the strings?

**Comment by ocean90** [comment]
I'm not sure if it's BOM related, but as mentioned in #52 4.3 doesn't support NULL values which GlotPress requires. So it seems like the plugin will only be compatible with 4.4+.

**Comment by toolstack** [comment]
@JRGould, the issue is that during the import with 4.3 blank strings were stored in the database instead of NULLs, then when you import again the SELECT statement used to find the privously imported translations is looking for NULLs not empty strings.

That then sends the import process in to a tailspin and it times out.  WP 4.4 adds support for storing NULLs to $wpdb which is what $gpdb supported and what GP expects.

**Comment by JRGould** [comment]
In my investigation of this issue, the tailspin was being caused because **every** string was different - strings from the DB all began with a non-printing character that wasn't found in the uploaded originals. It wasn't just NULL/empty strings. So I'm not convinced that that's what fixed the issue. 

Regardless, I'm happy to call this resolved if we're only worried about being compatible with 4.4 - but it may be worth looking into further if we're looking to add compatibility/migration from existing GP standalone installs.

**Comment by toolstack** [comment]
Something to keep in mind when we start work on the migration scripts.
