### ISSUE TITLE
Allow GlotPress tables to have a table prefix independent of the WP table prefix

### ISSUE THREAD

**Issue by bradt** [GlotPress/GlotPress#10]
...to make it easier for those moving from GlotPress standalone install.

**Comment by toolstack** [comment]
:-1: This could cause issues with multi-site, if we're breaking backwards compatibility in so many other places, why try and maintain it here?

**Comment by bradt** [comment]
It has nothing to do with backwards compatibility. It's just saving people the work of renaming their GP tables to match the WordPress prefix.

For example, let's say you have a GP install sharing a database with a WP install. Pretty typical. If the GP prefix is `gp_` and WP prefix is `wp_`, the plugin currently would require you to rename the `gp_*` tables to `wp_gp_` to get it to work.

I was thinking it would be nice if you could just add `define( 'GP_TABLE_PREFIX', 'gp_' );` to your wp-config.php and you wouldn't have to rename tables.

**Comment by toolstack** [comment]
I just think it's more trouble long term than the effort to rename the tables short term.

**Comment by ocean90** [comment]
Actually this is already possible, see https://github.com/deliciousbrains/GlotPress/blob/wordpress-plugin-dbi/gp-settings.php#L26-L28.

Do we want a constant or is the global var `$gp_table_prefix` enough?

Edit: But it seems like it doesn't work as expected…

**Comment by ocean90** [comment]
> Edit: But it seems like it doesn't work as expected…

Fixed in #63.

**Comment by toolstack** [comment]
I would think the variable is enough as long as we document it.
