### ISSUE TITLE
Create WP readme.txt

### ISSUE THREAD

**Issue by toolstack** [GlotPress/GlotPress#104]
We need a readme.txt file for when we submit to the plugin directory.

**Comment by ocean90** [comment]
The plugin directory supports a Readme.md too. Do we want an extra readme just for the directory?

**Comment by toolstack** [comment]
The plugin directory only kind of supports .md's as it doesn't support GitHub style markdown, only WP style markdown.

I think it make sense to have a properly formatted readme for both the plugin directory and GitHub.

Likewise there's probably different content we want in each one, .txt is going to have screenshots, header information, change log and other sections that the repo probably doesn't need to display on the front page.
