### ISSUE TITLE
Create banner image and a plugin icon for WordPress.org plugin directory

### ISSUE THREAD

**Issue by bjork** [GlotPress/GlotPress#108]
As per:
https://wordpress.org/plugins/about/faq/#banners

Related: #104

**Comment by ocean90** [comment]
…and a plugin icon.

**Comment by bjork** [comment]
Is the logo in http://blog.glotpress.org/ the official logo? Does anyone know if there is a better quality version of it somewhere?

Personally I do not think it is a very good logo and creating a new one could be considered.

**Comment by toolstack** [comment]
How about something like this (I have vector versions of them):

Some explanation of the design choices:
- The color was picked from the existing GlotPress banner on glotpress.org.
- The typeface is "Baskerville Old Face" which was the closest match to the existing GlotPress logo I had available.
- The logo design is based on the existing WordPress logo, I did not include the "oversized" font design (which merges the inner whitespace with the letter) as with the G, too much of it merged in to the inner white space.
- The "banner" image is more of a replacement for the glotpress.org banner as it doesn't work very well with the plugin directory.

Logo:

![glotpress-logo](https://cloud.githubusercontent.com/assets/9053749/10894400/5ff4c3d0-817c-11e5-9b6f-2e69d60a1b4f.png)

Banner:

![glotpress-banner](https://cloud.githubusercontent.com/assets/9053749/10894409/6c9ebd16-817c-11e5-98c5-2b47f2ac65e1.png)

Note: This is the limit of my artistic talent :wink:

**Comment by bjork** [comment]
I can get a professional to do a logo, but I first need a confirmation that it is needed.

**Comment by bradt** [comment]
I like the idea of the logo with teh G in the circle above. Seems inline with bbpress.org and buddypress.org logos. I'll see what I can come up with.

**Comment by deconf** [comment]
The banner won't work, because the plugin title will be displayed over the banner (in Plugin Directory). IMHO any banner containing a big text will look bad.

**Comment by adipop** [comment]
Hi,
I would like to propose a new logo for GlotPress plugin. 
If You like it I can propose a banner too :)

![glotpress-logo-blue](https://cloud.githubusercontent.com/assets/914417/11145653/1d3b5a1c-8a10-11e5-8eef-8e465d93daa9.png)
![glotpress-logo-button](https://cloud.githubusercontent.com/assets/914417/11145654/1d3dedea-8a10-11e5-9929-e7c9b5bd3554.jpg)

There is a .svg or .ai version of them, of course :)

**Comment by deconf** [comment]
I like the blue, flat version and the idea of having <strong>GP</strong> instead of a simple <strong>G</strong>.

**Comment by adipop** [comment]
Here you have several sizes (and colors).
![glotpress-logo-sizes](https://cloud.githubusercontent.com/assets/914417/11146343/3e7caa22-8a16-11e5-8ee2-424f63988855.jpg)

[v 1.0]

**Comment by toolstack** [comment]
@deconf, that assumes the banner image height is 100% and has no space at the bottom.  The banner was more for glotpress.org than the plugin directory though.

@adipop Flat version for sure, but I think it might look a little busy with the globe and GP, especially with them all flowing together.

**Comment by deconf** [comment]
@toolstack I wasn't talking about a possible overlap issue, my concerns are more about the visual impact of displaying the same text twice, using big fonts (the text from the banner and the plugin title).

**Comment by ocean90** [comment]
I think we should have something which doesn't look like bbPress or BuddyPress.

If you propose a logo/icon please also explain it a bit, like the reason for the form, the colors, the font type etc.

**Comment by adipop** [comment]
Hi @ocean90! Ok, I didn't know that it's preferable to have a different look than WordPress sign (bbPress or BuddyPress). I though of contrary :)
That's why I used the same font as in WordPress Logo, Mrs. Eaves, and starting from the WordPress sign construction I tried to create a similar feeling. 
I avoided one letter (G) because it led to the new Google G-logo. But because the two letters (from Glot and Press GP) didn't fill the circle as one letter (W), and because there was no graphical hint for global/i18n/etc. I choose to add the globe "embraced" by the two letters, with terminals resembling the one of W. Maybe for the very small icon size (32px) the globe can be a simple disk. If this "map" version for globe looks too complicated it can be substituted with a simpler one (a globe with two latitude and one longitude lines).

But if the resemblance with WordPress sign is not preferable, I could think at something else. 
Thanks for feedback! :)

**Comment by rmccue** [comment]
> That's why I used the same font as in WordPress Logo, Mrs. Eaves, and starting from the WordPress sign construction I tried to create a similar feeling.

Note that the logo itself is actually typeset in Dalliance; it's only the wordmark that's in Mrs Eaves. :)

**Comment by adipop** [comment]
Thanks Ryan, didn't know that and had to edit a little bit the serifs... :)
I'll try with Dalliance!

​

**Comment by rmccue** [comment]
Caution: Dalliance is a _very_ strange font, so I wouldn't be surprised if you're better off with a normal serif instead.

**Comment by adipop** [comment]
Indeed strange, It's useless for GP :)
![gp gp in dalliance](https://cloud.githubusercontent.com/assets/914417/11168645/bfe5af7e-8ba0-11e5-9018-0a7ca0121695.gif)
![glotpress in dalliance](https://cloud.githubusercontent.com/assets/914417/11168646/d1cdc1b8-8ba0-11e5-91e6-28226bff2d06.gif)

**Comment by adipop** [comment]
@deconf asked me to try with a simplified globe. Here are both variants:

![glotpress-logo-2var-round](https://cloud.githubusercontent.com/assets/914417/11179926/8f862c40-8c5f-11e5-9ea6-dd3a5ca159b1.png)

and the same on square:

![glotpress-logo-2var-square](https://cloud.githubusercontent.com/assets/914417/11179941/a6bd906a-8c5f-11e5-8e0f-a7e8b49e8efe.png)

**Comment by toolstack** [comment]
I think the simplified globe looks a lot like a basketball...

**Comment by adipop** [comment]
Right :) ...actually is the dribbble sign. So I make a correction and here is a version 3.
![glotpress-logo-var3](https://cloud.githubusercontent.com/assets/914417/11186323/d80b6262-8c89-11e5-85a6-86f7d6070ba9.png)

[v 1.0 and v1.1]

**Comment by deconf** [comment]
V1 square looks better, not having that white circle around does a lot. Here's a sample:

![plugin-directory-preview](https://cloud.githubusercontent.com/assets/5954813/11190989/7049c4bc-8ca1-11e5-9d0e-ffa7ae035c10.png)

**Comment by adipop** [comment]
I made another version in two variants with a larger and more clear globe and using a modern font - one of my favorites  - Helvetica (blod).
@deconf made a mockup for each of them, Thanks Alin.
![glotpress-logo-var5](https://cloud.githubusercontent.com/assets/914417/11191991/37611c80-8ca7-11e5-9b17-7a76dfc15a78.png)

[v 1.2]

![mockup-v5](https://cloud.githubusercontent.com/assets/914417/11192026/5fe919fa-8ca7-11e5-9115-ee23da228bc6.png)

and the last one:
![glotpress-logo-var4](https://cloud.githubusercontent.com/assets/914417/11192044/76485dd2-8ca7-11e5-8863-88209bf9114d.png)

[v 1.3]

![mockup-v4](https://cloud.githubusercontent.com/assets/914417/11192102/b5317d6c-8ca7-11e5-88d1-4037752329f2.png)

**Comment by javorszky** [comment]
Personal opinion: having the globe display North and South America, Europe and Africa isn't representative of the entire community (on account of Asia and Australia are missing).

I like the last one, square top right and mid bottom. The trefoil version adds too much visual noise imho.

**Comment by rmccue** [comment]
> Personal opinion: having the globe display North and South America, Europe and Africa isn't representative of the entire community (on account of Asia and Australia are missing).

Gotta cut somewhere off if you have a globe in 2D. :)

**Comment by javorszky** [comment]
> Gotta cut somewhere off if you have a globe in 2D. :)

![](http://alteagallery.com/jpegs/8335.jpg)

;)

**Comment by adipop** [comment]
That's a good point :) What about this?
![glotpress-logo-var6](https://cloud.githubusercontent.com/assets/914417/11204366/bd9cd168-8d06-11e5-83d8-f80171d8f68c.png)

[v 1.4]

**Comment by adipop** [comment]
and yet another one! (for simplifying references I named the versions below)

![glotpress-logo-var9](https://cloud.githubusercontent.com/assets/914417/11207347/62b98982-8d1d-11e5-81f1-0983591eaf13.png)

[v.1.5]

**Comment by toolstack** [comment]
How about something a little different:

![glotpress-logo-3](https://cloud.githubusercontent.com/assets/9053749/11212920/01c4fb86-8d07-11e5-9529-2ed872a84960.png)

**Comment by hugobaeta** [comment]
It’s great to see all the enthusiasm here; I was inspired by a few things I saw. Went back and forth with  @mattmiklic in a chat, and In the end decided to go for a more "traditional" approach, based on the intricacies of the [WordPress brand](https://make.wordpress.org/design/handbook/foundations/identity/).

This proposal uses the same typography as the WordPress logo. The Emigre Dalliance lowercase "g" in the circle was much more pleasant than their uppercase.

![GlotPress Logo Proposal](https://cldup.com/ohQI2tWYW8.png)

Here are some guidelines for it, similar to the ones for the WordPress logo:

![GlotPress Logo Guidelines Proposal](https://cldup.com/9AkPRNPAU8.png)

I'm not super crazy about the letter interactions in "Glot" – such a difficult word to typeset. So I typeset this, as an alternative proposal. It wouldn't have an icon to it necessarily:

![GlotPress Logo Guidelines Proposal](https://cldup.com/NcSOj57qFA.png)

Here are some glam-shots of both :stuck_out_tongue_winking_eye: 

![GlotPress Logo Proposal](https://cldup.com/X3hNgzcoH1.png)

![GlotPress Logo Proposal](https://cldup.com/4x6PTH5Uu5.png)

Let me know what you think and if any of these are worth pursuing.

**Comment by deconf** [comment]
IMO, a banner with a big text on it just won't work for the reasons mentioned above. I would rather go for something that represents or suggests what GP is and does in a banner and let the overlaying plugin title to take care of text . 

Regarding the logo when we use G in WP community everyone thinks at Google. GP is the abbreviation we use for GlotPress, so IMO it would make sense to have more than a G in a circle for the logo.

**Comment by rmccue** [comment]
> GP is the abbreviation we use for GlotPress, so IMO it would make sense to have more than a G in a circle for the logo.

Conversely, "WP" is the abbreviation for WordPress, but the logo is just a W :)

@hugobaeta Love the G!

**Comment by ocean90** [comment]
@deconf 

> Regarding the logo when we use G in WP community everyone thinks at Google

You should avoid _everyone_ if you don't have any proof for that. For example I don't think at Google when I see a G. G+ is another topic.

@hugobaeta 
I really like the lowercase "g" and would go with the alternative proposal for "GlotPress". I think it's OK to not use both near together. 

btw: I still think that GlotPress should have its own brand colors.

**Comment by toolstack** [comment]
@hugobaeta I like the lower case g as well from a visual perspective but it does kind of grinds on my nerves a bit from a grammatical perspective :wink:

I do think the lower case g is more reminiscent of Google's older logo they used for some of their icons (take a look at this [Wikipedia page](https://en.wikipedia.org/wiki/Google_logo#Favicon) for examples).

It may be too close from a trademark perspective.

@ocean90 any thoughts on what the brand colours might be?

**Comment by ocean90** [comment]
If we want to continue with the color scheme from WordPress maybe one of http://codepen.io/hugobaeta/full/RNOzoV/. Yellow, orange or purple are my favs.

**Comment by adipop** [comment]
@hugobaeta 
I like the "traditional" approach, too :) ...but I would not dismiss the capital G! With a little bit of extra-work I enhanced and corrected the extravagant G in a more lean one, of course keeping the W's flavor! Here are some steps and the final proposition, with an icon and a color proposition.
Hope you like like it as much as I do.

![glotpress-logo-work-new](https://cloud.githubusercontent.com/assets/914417/11271592/a5898c86-8ecf-11e5-89cd-a804b87ad7c2.jpg)

This can be a very good path for all the other major plugins - I allready know, GlotPress will be one ;)

**Comment by deconf** [comment]
@ocean90 sometimes a little good faith is required for a proper interpretation of a message, and a quick search on Slack and Forums.

**Comment by deconf** [comment]
@adipop Red?! Please don't :)

**Comment by toolstack** [comment]
I kind of like the Orange...

Though the stylized capital G looks more like a C with a J attached to it.

**Comment by adipop** [comment]
@deconf: is orange, not red, please! Not exactly the orange from the color scheme proposed by @ocean90. This is with the fire orange (#F56E28).

![glotpress-logo-g-fire-orange](https://cloud.githubusercontent.com/assets/914417/11272242/26c3df28-8ed4-11e5-965d-bb30acadc7ec.jpg)

@toolstack: funny, didn't saw that!

**Comment by ocean90** [comment]
@adipop Nice, can you make a third alternative where only "Glot" is in orange and icon + "Press" in gray?

**Comment by adipop** [comment]
Like this...
![glotpress-logo-g-fire-orange-2](https://cloud.githubusercontent.com/assets/914417/11272448/b0f1bfac-8ed5-11e5-8cf9-549a56526d55.jpg)

**Comment by ocean90** [comment]
> Though the stylized capital G looks more like a C with a J attached to it.

Now I can't unsee that...

**Comment by deconf** [comment]
@adipop I was on mobile and it seemed to be red, sorry. Anyway, the logos with <strong>GP</strong> are more suggestive.

**Comment by toolstack** [comment]
@ocean90 welcome to my world...

**Comment by bradt** [comment]
I like what @hugobaeta has come up with above. Here's my attempt...

![image](https://cloud.githubusercontent.com/assets/190095/11274595/ec2747b6-8eaf-11e5-8ead-0fb3d44ee5b4.png)

I liked how the lowercase "gp" go together in my code editor, so figured I'd try them in Helvetica in the medallion. I think they look great together. Very symmetrical.

Here's a couple of screenshots of the logo in the wild...

![image](https://cloud.githubusercontent.com/assets/190095/11276337/1d97b4c2-8eb8-11e5-9078-84abe7ebbafb.png)

![image](https://cloud.githubusercontent.com/assets/190095/11276478/9f107fa2-8eb8-11e5-8e36-22a56a4ee638.png)

![image](https://cloud.githubusercontent.com/assets/190095/11276347/2b615f36-8eb8-11e5-8df7-3a1c620ff986.png)

**Comment by adipop** [comment]
@ocean90 & @toolstack The calligraphic G is pretty close to the one proposed. Maybe you can now forget the CJ :)

![08edd5cd7f75a456af05dbb4144aab](https://cloud.githubusercontent.com/assets/914417/11275322/ceeab3fa-8ee5-11e5-8a2d-f80b4597af56.gif)

**Comment by toolstack** [comment]
Sorry, still see the CJ :disappointed: 

But I do like the symmetry of @bradt gp design.

**Comment by deconf** [comment]
@bradt I wonder if increasing the <strong>gp</strong> font size would affect the overall aspect.

**Comment by hugobaeta** [comment]
I understand this discussion is about specifically the banner and icon for the plugin, but it has derailed, inevitably, to the topic of branding. 

@bradt I had gone in the direction of playing with the GP as well, but did so in Mrs.Eaves Petite Caps.

@adipop The type purist in me can't deal with such heavy alterations to Dalliance's forms, specially because that G looks now like a mash of an uppercase and a lowercase G in one glyph. Maybe we should drop the idea of doing the "g" in a circle at all.

@ocean90 I can get on board with the idea of GlotPress color(s). And YES, thank you for mentioning the very broad [WordPress color palette](http://codepen.io/hugobaeta/full/RNOzoV/) – those extra hues were added for cases just like this one.

I revised my proposals a bit, added two colors I think would work well for this brand (avoiding conflict with BuddyPRess orange, and bbPress green, if that makes sense). In this revision, I pursued the isolated wordmark, but added a sattelite element (that doesn't necessarily work together with the wordmark - functions more like an alternative representation for specific contexts).

![GlotPress Revised Logo Guidelines](https://cldup.com/7BiSF0IAQ4.png)

I experimented with two colors and an added graphical element for texture. I created myself a quick stylistic vectorization of a world map. I think it could work well as a textural element! Experiments in Yellow and Purple:

![GlotPress Revised Logo Yellow](https://cldup.com/FPfZdtQvFy.png)

![GlotPress Revised Logo Purple](https://cldup.com/-aDGWvv_dF.png)

**Comment by samuelsidler** [comment]
I really like the last logo / wordmark. I especially like the purple one because no other *Press product is using that color right now.

**Comment by toolstack** [comment]
:+1: on the purple

The background map kind of cuts off too many parts (poor Australia is missing completely).  Perhaps a more abstract texture would be better.

**Comment by toolstack** [comment]
![purple-topbar](https://cloud.githubusercontent.com/assets/9053749/11280382/cf4ed94c-8ec3-11e5-9407-c6288989ba40.png)

**Comment by samuelsidler** [comment]
@toolstack I'm not sure I'd go that far. :) Perhaps use purple as a highlight. But we should do that in another issue.

**Comment by ocean90** [comment]
@bradt Nice idea!

@hugobaeta 
I like both colors, maybe the yellow one a bit more, because WooCommerce is purple.
I agree with @toolstack, let's add Australia before @rmccue wakes up. :smile:

**Comment by hugobaeta** [comment]
@toolstack @ocean90  Did some adjusting so we can see Australia and a bit of New Zealand ;)

![GlotPress Banner Review](https://cldup.com/sZBdeU-Bfw.png)

**Comment by hugobaeta** [comment]
@toolstack regarding the GlotPress UI design, I can create a styleguide for you guys with colors and typography if you'd like, but maybe do so in another ticket, yes?

(on a side note, it's kinda funny being involved somehow with GP again [after almost exactly 4 years](http://blog.glotpress.org/2011/10/18/rethinking-the-glotpress-ui/)!)

**Comment by toolstack** [comment]
Yea we can do a style guide after we get the logo/banner done as another ticket.

**Comment by rmccue** [comment]
> Did some adjusting so we can see Australia and a bit of New Zealand ;)

\o/

Love the latest from @hugobaeta, both purple and orange look lovely.

**Comment by deconf** [comment]
Both the logo and the banner are simple and suggestive, exactly what a plugin needs.

**Comment by bradt** [comment]
Nice work @hugobaeta. Love the map bg. Purple is nice too, though it does remind me of WooCommerce. And since Automattic bought WooThemes, does that make WooCommerce a .org project? :)

The only thing bugging me about your latest work is the uppercase GP in the medallion...
1. I think the gap between the letters could be tightened up a bit.
2. The serifs feel a bit awkward/clumsy.
3. Lowercase gp are much more symmetrical and look better together than uppercase.

I guess what I'm saying is that I like my medallion better. :stuck_out_tongue_winking_eye:

**Comment by JRGould** [comment]
I'm not a huge fan of the lowercase, sans-serif logo. It does have a very appealing symmetry, but it reminds me too much of British Petroleum:

![image](https://cloud.githubusercontent.com/assets/1509647/11492127/ba3fed4c-979d-11e5-8c9b-b4e2c6a7d0dd.png)

I like @hugobaeta's Mrs. Eaves version, as it's more in line with WP's branding. I also like the idea of the map background to the banner, but not a fan of the execution - would prefer a more high-fidelity, yet still very "vector" rendering.

**Comment by ocean90** [comment]
First of all, thanks for all the proposals! Great work! :tada:
We're now at the point where we have to make a decision.

From today's chat: https://wordpress.slack.com/archives/glotpress/p1449154576000420

> **ocean90**:
> Looking at the issue again, it seems like the decision about the graphic itself has already been made, at least by the currently-active team.
> I don't know about that.  I think we had a lot of discussion about the various proposals, but not a "this is the one" statement.
> **ocean90**: 
> The one from Hugo got a lot of positive feedback.
> So we probably just need a poll for the color.
> **bradt**:
> If anyone is at the Community Summit today, DM me if you want work on GlotPress.
> **gregross**:
> Agreed, but I think that was a way to improve on the design, not say it was the "one".  Several of the others had good positive feedback as well, Hugo's was just the last in that list.
> **ocean90**:
> @gregross: Which one is your favorite?
> **gregross**:
> Hugo's, I think it works well, but I want to make sure everyone else has a chance to vote for their favorite as well :smile:
> **bradt**:
> I think we should combine mine and Hugo's
> I like Hugo’s colours, map graphics, and typography
> but I prefer my medallion
> So, I guess that could be one of the options to vote for
> **gregross**:
> So let's give everyone another week to submit any updated designs they have and then we'll do a poll starting next week.
> **ocean90**:
> @rmccue, @JRGould, @deconf, @toolstack, @samuelsidler and I are for Hugo's, @bradt likes it too, but with his medallion. I'd call this a decision. I'm open for a poll for the color and a medallion change.
> (If one of the mentioned guys disagrees with that statement, please correct me.)

I'm currently not planning to do a poll for the graphic itself, maybe only one for the colors.
**But** I invite everyone to do a final proposal for his graphic. **The final decision will be made in the chat on December 10th @ 14:00 UTC.**

**Comment by chantalcoolsma** [comment]
Thought about all of them over the last few days. At first I liked the one with the globe (v1.3), but eventually I like the last one the most. Purple.

**Comment by bradt** [comment]
I could be wrong, but I think I've counted more people that are for the purple. Here's a couple of in-context screenshots...

![image](https://cloud.githubusercontent.com/assets/190095/11614305/b2d99d6e-9c0c-11e5-803f-dcd2e5d72ff7.png)

![image](https://cloud.githubusercontent.com/assets/190095/11614317/f0116090-9c0c-11e5-807e-99acc12f396c.png)

@hugobaeta Would be great to update https://wordpress.org/plugins/glotpress/ with the banner just after the meeting this week. Can you post the high res version here or in the Slack channel?

**Comment by chantalcoolsma** [comment]
@hugobaeta is it possible to shift the P in the logo a bit to the left? I think if the letter spacing is a bit less, it is just a bit better aligned. My feeling tells me that the upper right of the P is closer to the border than the upper left of the G.

**Comment by hugobaeta** [comment]
Talked to @ocean90 today, and finally managed to squeeze in some time to finish this. Apologies for the delay.

With the decision to move forward with my proposals, I spent a bit more time working on this direction. @chantalcoolsma / @bradt concerns - The concerns you commented on regarding the icon typesetting are taken care of - that proposal was a quick one to get the conversation going, I had always planned to go in and refine things. I hope you enjoy the ligature I created and the new spatial arrangement and proportions.

Here is the identity system for the new GlotPress plugin:

![glotpress-identity-system](https://cloud.githubusercontent.com/assets/1514660/11732598/9c8f28f2-9f5a-11e5-9385-9e6d9ed2e18b.png)

The icon was carefully sized and it's elements positioned. Here's a breakdown of what I did:

![glotpress-icon-guidelines](https://cloud.githubusercontent.com/assets/1514660/11732600/9fdcf58e-9f5a-11e5-964a-3392ad9441cc.png)

Finally, I created the images for the plugin, with an edited map (just outlines, rounder shapes).

![glotpress-plugin-assets](https://cloud.githubusercontent.com/assets/1514660/11732608/b6207d3e-9f5a-11e5-9aaa-715c921bdbe5.png)

## Plugin Assets
- [Plugin Icon (128x128)](https://www.dropbox.com/s/6yf2vi5lirzdc14/icon-128x128.png?dl=0)
- [Plugin Icon (256X256)](https://www.dropbox.com/s/7gc5sf8tnmxam8h/icon-256x256.png?dl=0)
- [Plugin Banner (772x250)](https://www.dropbox.com/s/oi0n9ibtx7kh2ng/banner-772x250.png?dl=0)
- [Plugin Banner (1544X500)](https://www.dropbox.com/s/esbmp5u1r44hmca/banner-1544x500.png?dl=0)

## Identity System Files
- [PDF (Editable in Illustrator)](https://www.dropbox.com/s/p8urz9nc3quyyaf/glotpress-2015-identity.pdf?dl=0)
- Illustrator (https://www.dropbox.com/s/ozujahfmbczx1pq/glotpress-2015-identity.ai?dl=0)

Hope everyone is happy with the direction this went! Everyone that contributed ideas should get props since this final version is a marriage of all the proposals and conversation that happened here. Let me know if you need any more assets or guidelines.

Cheers!

**Comment by chantalcoolsma** [comment]
Awesome! 👍

**Comment by bradt** [comment]
Awesome dude, great work! :tada:

**Comment by adipop** [comment]
Great work Hugo! ...still I feel that a descriptive element is needed in the logo - just the letters are kind of criptic. So this may be a better solution?!

![glotpress-2015-identity hugo baeta adi pop _glotpress identity presentation](https://cloud.githubusercontent.com/assets/914417/11745320/1176e31a-a020-11e5-994d-009d911af724.png)
![glotpress-2015-identity hugo baeta adi pop _icon guidelines](https://cloud.githubusercontent.com/assets/914417/11745329/1aa1925a-a020-11e5-8968-fa2b4c9bd1fd.png)
![glotpress-2015-identity hugo baeta adi pop _plugin icon retina](https://cloud.githubusercontent.com/assets/914417/11745338/285684dc-a020-11e5-83e3-0360060abdb7.png)
![glotpress-2015-identity hugo baeta adi pop _plugin banner retina](https://cloud.githubusercontent.com/assets/914417/11745389/7c37771e-a020-11e5-9a59-cca4bd7b541d.png)

**Comment by ocean90** [comment]
@hugobaeta Thanks for you work! The banner is now live: https://wordpress.org/plugins/glotpress/

**Comment by chantalcoolsma** [comment]
:+1: Looks nice!

**Comment by toolstack** [comment]
Woohoo!

**Comment by toolstack** [comment]
Created a [Wiki page](https://github.com/deliciousbrains/GlotPress/wiki/2.-Branding-and-Logos) for the design and closed the ticket.

Great work everyone!
