### ISSUE TITLE
Merge upstream changes

### ISSUE THREAD

**Issue by bradt** [GlotPress/GlotPress#11]

**Comment by ocean90** [comment]
@bradt Does it make sense to commit the changes first to the SVN branch which is synced with the git repo so we can merge them into this repo? Wouldn't like to lose the history.

**Comment by bradt** [comment]
You mean merge `wordpress-plugin-dbi` into `wordpress-plugin` ? If so, yes, that was my intention. `wordpress-plugin-dbi` was branched off of `wordpress-plugin`, so would be an auto-merge, no conflicts.

I was planning to merge the `package` branch into `wordpress-plugin`, then `wordpress-plugin` into `wordpress-plugin-api`. That a good plan?

**Comment by ocean90** [comment]
I'm not sure what the `package` branch is.

I was talking about https://glotpress.trac.wordpress.org/log/?action=stop_on_copy&mode=stop_on_copy&rev=1131&stop_rev=1063. These need to be committed first to https://glotpress.trac.wordpress.org/browser/branches/wordpress-plugin and will then be available in `wordpress-plugin`.

After (or before?) that we can merge `wordpress-plugin-dbi` into `wordpress-plugin`.

**Comment by ocean90** [comment]
Will do this today, without the SVN step. We can cherry-pick from https://github.com/GlotPress/GlotPress/tree/master.

**Comment by toolstack** [comment]
We're a little behind the master branch, new PR #43 created to bring over the latest changes.
