### ISSUE TITLE
Permissions locale list too long

### ISSUE THREAD

**Issue by toolstack** [GlotPress/GlotPress#122]
When adding permissions the locale list includes all locales instead of only those translation sets that exist in the project.

You shouldn't add permissions for translation sets that don't exist.

**Comment by toolstack** [comment]
There are two PR's for this, both accomplish the same thing but in different ways:
- the first adds an additional parameter to the end of gp_locales_dropdown() function to limit the list by project id
- the second adds a new function gp_locales_by_project_dropdown() with the project id as the first parameter of the function and the rest identical to gp_locales_dropdown()

**Comment by gilbitron** [comment]
Is there any particular reason for the alternate solution #131? Personally I think #123 is a cleaner solution.

**Comment by toolstack** [comment]
@ocean90 had a concern about adding the extra parameter at the end of the parameter list and readability, see https://wordpress.slack.com/archives/glotpress/p1446735005000158 

So I created an alternate version that self-documents better.

**Comment by gilbitron** [comment]
Fair enough. In that case should we close #123 and merge #131?

**Comment by toolstack** [comment]
I was waiting for some more feedback from @ocean90, I'm fine either way.
