### ISSUE TITLE
Should we break the fork with glotpress/glotpress or do something else?

### ISSUE THREAD

**Issue by toolstack** [GlotPress/GlotPress#132]
I'm opening an issue for this so we have a single place to track it.

The discussion started over on [Slack](https://wordpress.slack.com/archives/glotpress/p1446721968000031) about breaking the fork so that when creating pull requests the glotpress/glotpress branch would not be the initial fork selected to merge to.

The discussion continued in the weekly meeting [here](https://wordpress.slack.com/archives/glotpress/p1446736685000230) with general consensus that this seemed like a good idea.

**Comment by toolstack** [comment]
While, at first glance this seems like a good idea, the one issue I can see is that once the fork is broken off of glotpress/glotpress, merging back to the root tree might be an issue.

This then come down to what the future of GlotPress as a plugin is, if:
- It stays it's own codebase and does not merge back in to the original GlotPress git/svn repo, then breaking the fork makes perfect sense.
- the future plan is to move development back to the root git/svn tree it would seem to make more sense NOT to break the fork and continue as we are so we can merge all the way back without issue.

**Comment by rmccue** [comment]
This does _not_ change any of the code or version history, and merging will still work fine if we ever want to do that. The only thing it'll change is the GitHub UI so that this is no longer listed as a fork of glotpress/glotpress.

**Comment by toolstack** [comment]
Thanks @rmccue I wasn't sure if there were any future issues but if not then let the borking begin!

**Comment by ocean90** [comment]
Some questions from https://wordpress.slack.com/archives/glotpress/p1446736685000230

> @bradt: Does that also mean we can get the project to live at glotpress/glotpress-plugin (or similar) soon?

No, I don't know who the owner of the GlotPress organisation is.

> @bradt: I thought it meant divorcing ourselves from the standalone project and no longer merging upstream changes

Yes and no. We still can merge upstream changes.

> @toolstack: My understanding is that its asking github to split the deliciousbrains/glotpress fork away from the glotpress/glotpress parent.

Correct.

> @bradt: Might be harder to cherry-pick upstream changes

Not harder as before, although I'm not planning to continue with cherry-picking since the differences are too huge. It would be more work to fix all the merge conflicts. We can should just copy&paste the change. I also doupt that there are many upstream changes in future.

**Comment by ocean90** [comment]
@toolstack It's also not planned to merge the plugin into the existing standalone branch. We can just replace the default branch if we want.

**Comment by toolstack** [comment]
Sounds good.

**Comment by ocean90** [comment]
Done. :+1:
