### ISSUE TITLE
Projects: Remove personal option for source template

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress#143]
Introduced in b772d61842899a9627c39f302f97fd2a223fc0f4.

There is only a POST route, no GET route, means their is no UI. I don't have a serious use case for why such an option must exist.

**Comment by ocean90** [comment]
Actually there is an UI, hidden under Project actions.

<img width="1115" alt="bildschirmfoto 2015-11-10 um 14 47 04" src="https://cloud.githubusercontent.com/assets/617637/11063925/fee605ce-87b9-11e5-971d-9bd095b464ab.png">

**Comment by toolstack** [comment]
The only use case I can think of would be to allow the admin to point to a different source repository that had a web based editor.

For example, you could point the project level source at the public read only repository (like the wordpress SVN repo) and then point your personal source to your private GitHub repo where you do your development.

It's a little bit of a strange use case, but is there any harm in leaving it in?

**Comment by ocean90** [comment]
I don't think it's strange, it makes sense enough to keep it.

**Comment by toolstack** [comment]
:+1:
