### ISSUE TITLE
gp_append_meta() doesn't work

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress#145]
See https://glotpress.trac.wordpress.org/ticket/480

> `gp_append_meta()` doesn't even work for non user objects.. `$object_id_column` and `$slug` are not defined, It uses the wrong variable in the SQL string, etc, etc.

Are there any objections for removing `gp_append_meta()`?

**Comment by ocean90** [comment]
~~Can we use the Meta API `add_metadata`, `update_metadata`, and `delete_metadata` for the other functions?~~

**Comment by toolstack** [comment]
It doesn't appear to be used anywhere so remove it.

:+1:
