### ISSUE TITLE
Make plugin translation ready

### ISSUE THREAD

**Issue by polevaultweb** [GlotPress/GlotPress#15]
Kinda makes sense given the purpose of the plugin itself!

**Comment by ocean90** [comment]
The PR just adds the text domain and the `load_plugin_textdomain()` call. That's fine.

But there are some other issues:
- Placeholders aren't explained in a translators comment
- The use of `_n()` is wrong in some cases, like `_n('One translation rejected.', '%d translations rejected.', $ok, 'glotpress' ), $ok );`
- Strings like `__( 'edit', 'glotpress' )` should get a context:  `_x( 'edit', 'glossary', 'glotpress' )`
- `esc_attr( __( ) )` => `esc_attr__( )`
- `echo _x( )` => `_ex( )`

How do we want to handle these? Move them into new issues?

**Comment by toolstack** [comment]
I'd vote for handling them as separate issues, they're all valid but shouldn't be a show stopper for 1.0  (maybe with the exception of _n()) , just something we can work on from release to release.

**Comment by polevaultweb** [comment]
+1 for a new 'enhancement' issue for after 1.0
