### ISSUE TITLE
Remove unused table api_key

### ISSUE THREAD

**Issue by toolstack** [GlotPress/GlotPress#150]
The api_key table doesn't seem to be used, let's remove it.

**Comment by ocean90** [comment]
Introduced in https://glotpress.trac.wordpress.org/changeset/390 `¯\_(ツ)_/¯`

**Comment by ocean90** [comment]
@toolstack The API code shouldn't be removed, it's definitely used.

**Comment by toolstack** [comment]
Ok, I'll revert the change in the PR.

**Comment by nb** [comment]
Yeah, we had grander plans for the API at that time. Next time :)
