### ISSUE TITLE
Merge back to master

### ISSUE THREAD

**Issue by toolstack** [GlotPress/GlotPress#167]
Now that we have broken the fork, we should merge back the wordpress-plugin-dbi branch back to the master branch to simplify things.

**Comment by ocean90** [comment]
Can't we just delete the master branch and "rename" the wordpress-plugin-dbi branch?

**Comment by rmccue** [comment]
:point_up: that's the best solution, IMO

**Comment by toolstack** [comment]
:+1: to delete and rename then.

**Comment by toolstack** [comment]
As per the [Slack discussion](https://wordpress.slack.com/archives/glotpress/p1450363162000820), we'll delete and rename the branch just before the 1.0 release to avoid breaking too many PR's but avoid having to rewrite any release scripts we build.
