### ISSUE TITLE
Replace Validator with Translation Editor

### ISSUE THREAD

**Issue by deconf** [GlotPress/GlotPress#175]
What do you think about replacing the <strong>Validator</strong> title with <strong>Translation Editor</strong>?

Also see: https://make.wordpress.org/polyglots/glossary/#translation-editor

**Comment by chantalcoolsma** [comment]
Agree. We already translated "Validator" as "Redacteur" (Editor) in Dutch (nl_NL)

**Comment by ocean90** [comment]
I don't think we should change it in GlotPress, Translation Editor is specific to translate.wordpress.org.

**Comment by deconf** [comment]
The discussion around the change we've made on t.w.org is the main reason behind the above suggestion, and of course to make communication easier between t.w.org users and GP users.

**Comment by samuelsidler** [comment]
I agree with @ocean90. This change doesn't make sense for GlotPress-proper. We only use it on translate.wordpress.org because it makes sense within the context of WordPress.org. For others who use and install GlotPress, this change won't make as much sense.
