### ISSUE TITLE
Rethink directory structure

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress#176]
From https://github.com/deliciousbrains/GlotPress/pull/163#issuecomment-160195452

> Idea:
> Move /tests/bin to /bin
> Move /tests/\* to /tests/phpunit/*
> Move /tests/phpunit/test_.php and /tests/phpunit/tests_/ to /tests/phpunit/tests/
> If we start to write JS tests they can be placed into /tests/qunit and/or a release script can be in /bin. 

Thoughts?

**Comment by toolstack** [comment]
> Move /tests/bin to /bin

I don't like this as everything in the directory relates to testing only.  Leaving it in tests makes it easy to remove the entire test suite when we want to deploy the plugin to the plugin repository.

> Move /tests/\* to /tests/phpunit/*

:+1:

> Move /tests/phpunit/test_.php and /tests/phpunit/tests_/ to /tests/phpunit/tests/

Moving the tests to their own directory makes sense, but the path looks a little strange with two "tests" directories in it.  Would it make sense to rename the top level to "testing" or something else?

**Comment by ocean90** [comment]
> Leaving it in tests makes it easy to remove the entire test suite when we want to deploy the plugin to the plugin repository.

The deploy script is probably a script which belongs to a `/bin` directory, so it would be just the test scripts.

**Comment by toolstack** [comment]
So maybe leave /tests/bin alone and create a /bin for the deployment script?  Or maybe a /deploy directory?

**Comment by toolstack** [comment]
This was complete in a previous release.
