### ISSUE TITLE
Release Process

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress#177]
> how is the WP plugin directory getting updated?  is it syncing from wordpress-plugin-dbi or somewhere else or manually? - @toolstack 

I'm thinking a script like https://github.com/WP-API/WP-API/blob/develop/bin/release.sh would be handy. What else do we have?

Related: #176

**Comment by toolstack** [comment]
I took a look at the release script and it has a few limits (user id must be the same as w.org, doesn't handle deleted files, doesn't check for the tag already existing in svn).

I've modified it for use in my GP plugins, still testing it but it takes care of the above and some other items, the updated script can be found [here](https://github.com/toolstack/gp-additional-links/blob/master/bin/release.sh).

**Comment by ocean90** [comment]
> @ocean90: The script from above is the latest?
> @toolstack: No, grab the one from https://github.com/toolstack/gp-machine-translate, it's slightly newer.

**Comment by toolstack** [comment]
I've create a new repo for the script and added some documentation here: https://github.com/toolstack/git-to-wp-plugin-dir-release-script
