### ISSUE TITLE
Breadcrumb on locale page points to root directory

### ISSUE THREAD

**Issue by chantalcoolsma** [GlotPress/GlotPress#181]
The breadcrumb on the locale page (gp-templates/locale.php) doesn't point to /glotpress/languages/. In stead it points to /languages, which returns a 404 page.

Steps to reproduce:
1. http://example.dev/glotpress/
2. Click locales in header
3. Click on a locale
4. Click the Locales breadcrumb

Don't know if this is related to the other rewrite tickets.

**Comment by toolstack** [comment]
Just a missing gp_url() call in the template file, change line 5 in gp_template/locale.php from:

`$breadcrumb[] = gp_link_get( '/languages', __( 'Locales', 'glotpress' ) );`

to

`$breadcrumb[] = gp_link_get( gp_url( '/languages' ), __( 'Locales', 'glotpress' ) );`

There could be more of these cases left in the code somewhere as well.

**Comment by chantalcoolsma** [comment]
@toolstack do you make a PR?

**Comment by toolstack** [comment]
Haven't yet, go ahead if you like, if not I'll do one in a bit.

**Comment by chantalcoolsma** [comment]
On it :+1:
