### ISSUE TITLE
Integrate with WP's user profile.

### ISSUE THREAD

**Issue by toolstack** [GlotPress/GlotPress#196]
Currently the GP profile is a stand alone affair, which is fine, but we should include the same settings in the WP user profile as well.

**Comment by ocean90** [comment]
Chat: https://wordpress.slack.com/archives/glotpress/p1456411998000328

This can be 1.1 with a MVP:
- Move profile edit part into its own template
- Make the profile post handler accept an user ID

**Comment by toolstack** [comment]
Updated the PR as discussed.
