### ISSUE TITLE
Simplify load_plugin_textdomain() call

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress#199]
We'll never ship with translations in a /languages directory. `load_plugin_textdomain( 'glotpress' );` is sufficient.

**Comment by toolstack** [comment]
Could there be a use case for a site wanting to override the default translation files and use their own?

I'm still thinking simplification would be good but perhaps something like:

```
if ( !defined( 'GP_LANGUAGE_PATH' ) ) {
    define( 'GP_LANGUAGE_PATH', false );
}

load_plugin_textdomain( 'glotpress', false, GP_LANGUAGE_PATH );  
```

So a site could override the path via the wp-config file without having to recopy their custom files each time GP is upgraded?

**Comment by ocean90** [comment]
If there is a use case, `load_textdomain()` provides three hooks which can be used instead.

**Comment by toolstack** [comment]
What do you think the likelihood of a use case is?

If it's pretty low leaving it to the hooks is fine, but if it would be more common then I think it would better to have it clear in GP how to do it.

**Comment by ocean90** [comment]
@toolstack Dunno, I thought you have one. :smile:

**Comment by toolstack** [comment]
@ocean90 Nope, just playing devils advocate on that one :smile: 

I see you merged the PR so I'm fine with closing it as is.

**Comment by toolstack** [comment]
Or I was just imagining I saw the PR merged :smiling_imp:, so I'm fine with merging the PR.
