### ISSUE TITLE
Add warning and disable the plugin if permalinks are not set.

### ISSUE THREAD

**Issue by toolstack** [GlotPress/GlotPress#218]
GlotPress requires permalinks to be set, so just like unsupported versions of WordPress, we should add an admin notice and disable the plugin if they don't exist.

**Comment by ocean90** [comment]
I'm not sure if we really have to _disable_ the plugin. A warning should be fine. We could also try to enable them via `wp_install_maybe_enable_pretty_permalinks()`, see https://github.com/WordPress/WordPress/blob/06a3f799e744578ccae2741534dfc5949606b65b/wp-admin/includes/upgrade.php#L279.
