### ISSUE TITLE
Java i18n support

### ISSUE THREAD

**Issue by IvanRF** [GlotPress/GlotPress#222]
Hi guys, I'm testing the plugin and I think I could use it for a Java project.

However, I found that under the "Import Originals" section there is no option for Java `.properties` files. The format is similar to iOS `.strings` files but it not compatible. I tested it and it does not find strings.

An example of Java format:

```
# Comments
Find=Find
ReplaceWith=Replace with
```

More info here: 
[Properties File Format](https://docs.oracle.com/cd/E23095_01/Platform.93/ATGProgGuide/html/s0204propertiesfileformat01.html)
[Internationalizing the Sample Program](https://docs.oracle.com/javase/tutorial/i18n/intro/steps.html)
[.properties wiki](https://en.wikipedia.org/wiki/.properties)

**Comment by ocean90** [comment]
Looks interesting! Can you provide a Pull Request for it?

**Comment by IvanRF** [comment]
Are the files at `/gp-includes/formats/` the same for both projects? (GlotPress & GlotPress-WP)

**Comment by ocean90** [comment]
No, they are slightly different.

**Comment by toolstack** [comment]
@IvanRF can you take a look at [this branch](https://github.com/GlotPress/GlotPress-WP/tree/222-java-properties-support) and see if it generates the right file format?

**Comment by IvanRF** [comment]
@toolstack ok, I'll test it.
Looking at the code, will `preg_match( '/^(.*) = (.*)$/', $line, $matches )` work when there are no spaces before/after `=`, eg`Find=Find`?

**Comment by toolstack** [comment]
No, but I'm more concerned if it generates the right format at the moment more than if it can read it back in.

**Comment by toolstack** [comment]
Something else to try will be to make a string that contains an `=`.  I didn't find details on how to handle that case in the documentation yet.

**Comment by IvanRF** [comment]
> Something else to try will be to make a string that contains an =. I didn't find details on how to handle that case in the documentation yet.

http://stackoverflow.com/questions/2406975/how-to-escape-the-equals-sign-in-properties-files

**Comment by IvanRF** [comment]
Some things I don't know where to add:
- on Java, locale separator in the file name is `_` and not `-`. Example `Labels_es.properties`
- lines starting with `!` are also comments

**Comment by toolstack** [comment]
The filename is more difficult, even for the po files this is a problem.  You might want to look at [this plugin](http://glot-o-matic.com/gp-use-slug-for-downloads).

For the comments, it's here: https://github.com/GlotPress/GlotPress-WP/blob/222-java-properties-support/gp-includes/formats/format_properties.php#L94

**Comment by IvanRF** [comment]
I made a test project on Java:
- keys can't have spaces. [See this](http://stackoverflow.com/questions/2108103/can-the-key-in-a-java-property-include-a-blank-character)
- there are issues with the file encoding. Every character has an extra space and the file starts with `ÿþ` which is also taken as a resource string.

**Comment by IvanRF** [comment]
If I use the generated file as a `ResourceBundle` this is what I get (examples for `'key' >> 'value'`):

![11-2-2016 9-35-19 p- m-](https://cloud.githubusercontent.com/assets/6751650/12995614/73889e8c-d107-11e5-957d-1a7bc962114c.png)

**Comment by toolstack** [comment]
That kind of goes against what the other documentation says about how keys work but it's easy enough to escape them.

I thought we might have to drop the file encoding bytes.

Try the branch now.

**Comment by IvanRF** [comment]
I had tried escaping the spaces on the key before, now without the file prefix they work.

Well, keys look fine but now we do have encoding issues: `'Follow Me' >> 'SÃ­gueme'` (it should have an accent mark `Sí­gueme`)

**Comment by toolstack** [comment]
Can you do some research and see what encoding Java is expecting the file to be in?

**Comment by IvanRF** [comment]
It uses `ISO-8859-1`. According to the wikipedia link:

> The encoding of a .properties file is ISO-8859-1, also known as Latin-1. All non-Latin-1 characters must be entered by using Unicode escape characters, e.g. \uHHHH where HHHH is a hexadecimal index of the character in the Unicode character set. This allows for using .properties files as resource bundles for localization. A non-Latin-1 text file can be converted to a correct .properties file by using the native2ascii tool that is shipped with the JDK or by using a tool, such as po2prop,[1] that manages the transformation from a bilingual localization format into .properties escaping.

More detail [here](http://stackoverflow.com/questions/4659929/how-to-use-utf-8-in-resource-properties-with-resourcebundle) and in the [Java docs](http://docs.oracle.com/javase/8/docs/api/java/util/Properties.html#load-java.io.InputStream-).

**Comment by IvanRF** [comment]
I just sent the PR for encoding. Now, exporting is working fine with Java :+1: 

Only remains: locale separator in the file name is _ and not -. Example Labels_es.properties

**Comment by toolstack** [comment]
@IvanRF I tried that before but it doesn't seem to encode in the right "\uHHHH" format.

I just pushed a change to the branch that should give the right output, can you give it a try?

**Comment by IvanRF** [comment]
@toolstack I tested the latest change, using `json_encode` works fine too.

**Comment by IvanRF** [comment]
@toolstack what's the purpose of this never used variable `public $exported = '';` in all format files?

**Comment by toolstack** [comment]
@IvanRF the filename format should be correct now as well.

**Comment by IvanRF** [comment]
@toolstack the `public $exported = '';` variable is never used in this and other formats.

**Comment by IvanRF** [comment]
> the filename format should be correct now as well.

Excellent! I tested two locales and it's taking the filenames correctly.

**Comment by toolstack** [comment]
$exported is a hold over from the old code, we'll clean it up later.

I took the json encoding off the property names as that conflicts with the escaping of spaces and equal signs.

Also started working on the import code, not quite working yet.

**Comment by IvanRF** [comment]
@toolstack Moving to the `Import`, here you have some files for testing: [resources](https://github.com/IvanRF/MassiveFileRenamer/tree/master/src/com/ivanrf/renamer/resources).

Right now, the "Import Originals" is throwing some php errors with those files or exported ones. Also, fails to import to a locale but without php errors :)

**Comment by IvanRF** [comment]
> I took the json encoding off the property names as that conflicts with the escaping of spaces and equal signs.

In my tests I used spaces and ':' in the keys and there were no issues with json encoding

**Comment by IvanRF** [comment]
Oh, I can see the unicodes now in the files like `\u00e`.

**Comment by IvanRF** [comment]
ouch, now the slashes are broken on the translations: `<\/strong>` or `'http:\/\/domain.com\/`

**Comment by toolstack** [comment]
Probably need to remove the escape() from line 19:

```
$translation = empty( $entry->translations ) ? $entry->context : $this->escape( $entry->translations[0] );
```

**Comment by IvanRF** [comment]
yes, it is that. I just test it.

**Comment by IvanRF** [comment]
I found some examples from the JDK core which have several locales: [rmi/server/resources](https://github.com/frohoff/jdk8u-jdk/tree/master/src/share/classes/sun/rmi/server/resources).
They could be useful for testing imports since they have unicode strings.

**Comment by toolstack** [comment]
@IvanRF can you test the current branch, I think it should be functional now.

**Comment by IvanRF** [comment]
@toolstack Import originals worked as expected. I love the idea of saving the key as `Context` and showing the user the actual string, awesome!

On the other hand, Import translations failed.
`Fatal error: Call to a member function set_status() on a non-object in gp-includes\things\translation-set.php on line 146`

I tested it with my [simple project](https://github.com/IvanRF/MassiveFileRenamer/tree/master/src/com/ivanrf/renamer/resources). It failed importing `es` translations. First 5 translations were loaded, so I'm guessing this line make it fail:
`MatchCase=Coincidir mayúsculas/minúsculas`

**Comment by toolstack** [comment]
@IvanRF give it a try now.

**Comment by IvanRF** [comment]
@toolstack for my resources worked excellent! :+1:  but...

I tested also the **[RMI resources](https://github.com/frohoff/jdk8u-jdk/tree/master/src/share/classes/sun/rmi/server/resources)**. For Spanish stopped at this line:
`rmid.unfound.java.home.property=ActivatorImpl: no se ha encontrado java.home`

Maybe the issue is because it has `=` and `:`, it should divide key/value according to the first of those it finds.

In addition, from the first 8 strings that could load before reaching that line, this string was loaded:
`la opci\u00F3n -port requiere un argumento`

So, the unicode was not decoded. I think it is case-sensitive. When I tested my project, it saved `\u00f3` for the `ó` when exporting, and reimporting the same file worked. That is, it worked for `\u00f3` but not for `\u00F3`.

**Comment by toolstack** [comment]
I thought the occurrence of a separator in the string might be a problem, I'll have to replace the grep with a more complex function.

I'll double check the case sensitivity on the import.

**Comment by toolstack** [comment]
Yep, the regex only matched lower case, I'll update it.

**Comment by toolstack** [comment]
@IvanRF Ok, I've committed a fix for both, give it a try again.

**Comment by IvanRF** [comment]
@toolstack ok, I tested it again and now it works for all cases :+1: 

I had doubts with accessing `$line[ $location - 2 ]` without checking `$location >= 2`, but it could only happen if the line starts with `=`.

Well, I will be waiting for the GP 1.1.0 :smile:

**Comment by toolstack** [comment]
Yep, I'll probably add a test just to make sure, but it's an invalid line in the properties file anyway.
