### ISSUE TITLE
Clean up scrutinizer warnings/issues

### ISSUE THREAD

**Issue by toolstack** [GlotPress/GlotPress#237]
[Scrutinizer](https://scrutinizer-ci.com/g/GlotPress/GlotPress-WP/) is reporting warnings and issues with the codebase, this is a parent issue to track the cleanup of them.

**Comment by toolstack** [comment]
Leaving open for the time being as a placeholder for one final review of scrutinizer.

**Comment by ocean90** [comment]
Closing as fixed for 1.1
