### ISSUE TITLE
Translation Propagation: Change the default status of propagated translations to waiting

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress#247]
See https://glotpress.trac.wordpress.org/ticket/327 and https://glotpress.trac.wordpress.org/changeset/1144.
- Using "current" as the default status is leveraging the permission system.
- Use only "current" if the current user can approve translations in the new translation set.
- Don't propagate a translation if the current user isn't allowed to edit/submit translations in the new translation set.

**Comment by toolstack** [comment]
:+1:
