### ISSUE TITLE
Translation Propagation: Don't propagate an equal existing waiting translation

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress#250]
If a user approves a translation and it gets propagated to a translation set where the user can't approve translations then the translation gets added as waiting. The same happens also if an equal translation exists already. This behaviour should be prevented.

Related: https://glotpress.trac.wordpress.org/changeset/1092

**Comment by ocean90** [comment]
Thinking about the best approach to avoid duplicate entries: Is it a pre-check like https://glotpress.trac.wordpress.org/changeset/1092 or would a UNIQUE constraint be better because it catches all cases?

**Comment by ocean90** [comment]
Related: Do not allow creation of duplicate translation sets. – https://glotpress.trac.wordpress.org/changeset/381

**Comment by ocean90** [comment]
We can't use an UNIQUE index because the fields translation_2 - translation_5 can be NULL.

In case you want to test this too:

```
ALTER TABLE wp_gp_translations ADD UNIQUE KEY `original_id_translation_set_id_translations_status` (`original_id`, `translation_set_id`, `translation_1`(149), `translation_2`(149), `translation_3`(149), `translation_4`(149), `translation_5`(149), `status` );
```

**Comment by toolstack** [comment]
Why should the behaviour (from the original topic) be avoided?  What should it be?

I can see when the equal translation exists, it should just be dropped, but if a different translation exists then waiting seems like the right state.  A validator can then chose which is more appropriate for the project and either approve or reject it.

**Comment by ocean90** [comment]
Which original topic do you mean? And yes, this is just about equal translations.

**Comment by toolstack** [comment]
> Which original topic do you mean?
> 
> > If a user approves a translation and it gets propagated to a translation set where the user can't approve translations then the translation gets added as waiting. The same happens also if an equal translation exists already. This behaviour should be prevented.

I read the "This behaviour should be prevented" as applying in both cases, but if we're just talking about equal translations, then should we just not propagate the translation?
