### ISSUE TITLE
Standardize on tables for data display

### ISSUE THREAD

**Issue by toolstack** [GlotPress/GlotPress#263]
The majority of GlotPress data is displayed in tables, with two exceptions:
1. the projects list
2. the permissions list

These two areas are represented as html ul's.

For consistency we should standardize on tables.

**Comment by ocean90** [comment]
Moved to future because we want to focus on the new design which will probably not rely on heavy tables.

**Comment by toolstack** [comment]
Sounds more like `wontfix` than future, no point keeping it open if it won't get merged.

**Comment by ocean90** [comment]
Closing as _wontfix_ because tables are 🙈 and https://github.com/GlotPress/GlotPress-WP/issues/263#issuecomment-192290306.
