### ISSUE TITLE
Child projects are inaccessible if permalinks have trailing slash

### ISSUE THREAD

**Issue by toolstack** [GlotPress/GlotPress#265]
If the permalink structure has a trailing slash in it and you create a child project, that project is inaccessible because $project->update_path() does not trim the trailing slash, but the $project->by_path() does.

**Comment by ocean90** [comment]
Noticed the same a few days ago too, thanks for creating the issue. :+1:

It's important that we store the paths without trailing slashes so we're compatible with a later switch to a non-trailing slash structure.
Looking at `GP_Project->regenerate_paths()` and it seems to have the same issue.

**Comment by toolstack** [comment]
Updated the PR with the regenerate_paths() fix.
