### ISSUE TITLE
Make translation sets deletable

### ISSUE THREAD

**Issue by shield-9** [GlotPress/GlotPress#267]
Currently, we cannot delete translation sets if it is created by mistake.

Related: #92

**Comment by ocean90** [comment]
Trac ticket: https://glotpress.trac.wordpress.org/ticket/186

What should happen if a set has already translations?

**Comment by toolstack** [comment]
Delete the translations associated with the set.

After the set is deleted they're just dead weight in the database as you can no longer access them.

**Comment by shield-9** [comment]
+1 for _Delete the translations associated with the set_.
