### ISSUE TITLE
Translations: Store user_id of validator/approver

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress#293]
This would allow us to show the name of a validator in the "meta" sidebar like
<img width="305" alt="approver" src="https://cloud.githubusercontent.com/assets/617637/13206020/196e8c58-d8f6-11e5-8dc8-d36a43cedb93.png">

**Comment by toolstack** [comment]
Seems like a good idea.

**Comment by ocean90** [comment]
Should this be a more general field which contains the user ID of the last edit? This would allow us to use it for rejects too.

```
Translated by: User 1
if status = current
   Approved by: last_edited_user
elseif status = rejected
   Rejected by: last_edited_user
```

Should this be a meta field attached to the translation or a new table column in the database?

**Comment by toolstack** [comment]
I think it should be the id of the user that made the last status change to the translation.

I'd tend to add this as a new column only to avoid another query.

**Comment by yoavf** [comment]
I'd like to move this forward - @ocean90 are you ok with an additional column?

**Comment by ocean90** [comment]
@yoavf See the related [discussion on Slack](https://wordpress.slack.com/archives/glotpress/p1463504761000629). We have to make sure that all current workflows can be handled with a new column.

Maybe #209 (history/log/notes per translation) is a better idea for this?

**Comment by mhsdef** [comment]
FWIW I agree with @toolstack. AFAIK, in a normal flow, every translation requires the validation step so it seems integral to the translation record entity.

**Comment by ocean90** [comment]
Related discussion on Slack: https://wordpress.slack.com/archives/glotpress/p1464715578000943

@yoavf Let's try the additional column approach.
