### ISSUE TITLE
Things: Introduce `after_delete()` method and new actions

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress#294]
There is [`after_save()` and `after_create()`](https://github.com/GlotPress/GlotPress-WP/blob/master/gp-includes/thing.php#L310-L316), but no `after_delete()` yet.

`after_delete()` would be helpful to extend the CRUD actions like [translations](https://github.com/GlotPress/GlotPress-WP/blob/master/gp-includes/things/translation.php#L329-L337) or [originals](https://github.com/GlotPress/GlotPress-WP/blob/master/gp-includes/things/original.php#L315-L318) already have.

**Comment by toolstack** [comment]
PR #271 includes this feature now.
