### ISSUE TITLE
Make rows clickable on translations table

### ISSUE THREAD

**Issue by IvanRF** [GlotPress/GlotPress#298]
Currently, a user has to double click or click on the "Details" link in order to write a translation. It would be much better if the complete row can be clicked (one click) and the link/hand cursor is shown.

That is, apply this same UI:
![27-2-2016 2-22-11 p- m-](https://cloud.githubusercontent.com/assets/6751650/13374285/ae8d4f92-dd5e-11e5-9187-763874e8e412.png)

for this table:
![27-2-2016 2-23-02 p- m-](https://cloud.githubusercontent.com/assets/6751650/13374289/b6ad2954-dd5e-11e5-84f4-ecbb08f34710.png)

**Comment by IvanRF** [comment]
Related: [issue #263](https://github.com/GlotPress/GlotPress-WP/issues/263)

**Comment by toolstack** [comment]
https://wordpress.org/plugins/gp-single-click-edit/

**Comment by IvanRF** [comment]
@toolstack it's amazing how you have a plugin for everything :smile: :+1:

**Comment by toolstack** [comment]
What can I say, I'm the king of GlotPress plugins :wink:.

**Comment by IvanRF** [comment]
@toolstack are you sure about closing this issue?
It is not good for user experience to have to guess that you need to double click text in order to some UI to appear and allow you to translate text. Neither does a "Details" link has to do with "Translate".

**Comment by IvanRF** [comment]
@toolstack when I say this, I'm thinking on an inexperienced user wanting to help with translations on a project, not an IT guy who eventually will find the way to send a translation.

**Comment by toolstack** [comment]
That's why the primary interface for opening the details is the "Details" at the right side of the column.

Until I actually wrote the single click plugin, I didn't even know that double click was an option :smile:.

**Comment by ocean90** [comment]
I'm fine with showing the pointer cursor, but the double-click is fine as is because it lets you select a translation.
