### ISSUE TITLE
Does not work on nginx webserver

### ISSUE THREAD

**Issue by c-schmitz** [GlotPress/GlotPress#299]
While the LAMP stack (Linux + Apache + MySQL + PHP) is very popular for powering WordPress, Nginx in place of Apache is quickly becoming the market leader, especially on high traffic sites. WordPress supports Nginx completely, and some of the largest WordPress sites in the world, such as WordPress.com, are powered by Nginx. 

However the Glotpress plugin (1.01) does not work at all on nginx.
Our webserver is properly configured according to https://codex.wordpress.org/Nginx#General_WordPress_rules

However the Glotpress path cannot be opened/reached - no matter if you open the /glotpress/ URL or set the according directive in the wp-config.php - you always end up on the standard wordpress home page.

**Comment by ocean90** [comment]
I'm using GlotPress on a Nginx server and it's working for me. What are your permalink settings?

**Comment by c-schmitz** [comment]
That was it! Thank you very much! Please disregard my rambling ;)

**Comment by meglio** [comment]
My permalink setting is to use the post name, but I can't access `/glotpress` either.

UPD. I just realized I have to use `/projects/` and not `/projects`.
