### ISSUE TITLE
Translations: Include check button for case-sensitive search

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress#312]
From https://glotpress.trac.wordpress.org/ticket/151 by @zodiac1978:

> If you search for something like this: "Wordpress" And you want to replace it with "WordPress" (p -> P) you found a lot of crap you didn't looking for. A check button for switching on case sensitive search would be helpful.

**Comment by IvanRF** [comment]
while you are on the subject, you could include a check button for exact match search :smile:
