### ISSUE TITLE
Translation Sets: Validate slugs on saving

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress#329]
Related: #328 

The slug field should be validated/sanitized.

**Comment by toolstack** [comment]
And auto generated if it doesn't exist.

**Comment by ocean90** [comment]
@toolstack The default value is already `default`. If the field doesn't exist the user should get an error.

**Comment by toolstack** [comment]
I implemented a default handler if it's missing, following along the same logic as the project slug.
