### ISSUE TITLE
Prefix all GlotPress Action/Filters with "gp_"

### ISSUE THREAD

**Issue by toolstack** [GlotPress/GlotPress#33]
The GlotPress action/filters currently are a mix of "action_desc_here" and "gp_action_desc_here".

To avoid conflicts with other WordPress plugins, we should prefix all action/filters in GlotPress with "gp_" (that are GlotPress action/filters of course, not WordPress action/filters the plugin will use).

**Comment by bradt** [comment]
:+1:

**Comment by ocean90** [comment]
Let's do this.
