### ISSUE TITLE
Pass previous state to GP_Thing::after_save()

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress#335]
Example for `GP_Project`

``` php
/**
 * Executes after saving a project.
 *
 * @since 1.0.0
 *
 * @param GP_Project Project before the update.
 * @return bool
 */
public function after_save( $project_before ) {
    /**
     * Fires after saving a project.
     *
     * @since 1.0.0
     *
     * @param GP_Project $project The project following the update.
     * @param GP_Project $project_before The project before the update.
     */
    do_action( 'gp_project_saved', $this, $project_before );

    // TODO: pass the update args to after/pre_save?
    // TODO: only call it if the slug or parent project were changed
    return ! is_null( $this->update_path() );
}
```

Use case: The Rosetta Roles plugin caches the child IDs of a project, see https://meta.trac.wordpress.org/browser/sites/trunk/wordpress.org/public_html/wp-content/plugins/wporg-gp-rosetta-roles/wporg-gp-rosetta-roles.php?rev=2275&marks=49,50,110-122,309-332,362-372#L42. This cache needs only to be invalidated if either the parent ID of a project changes or a new project is created. Currently it gets also invalidated if the name or the description has changed.

**Comment by toolstack** [comment]
Seems like a good idea, should we pass the after save state as well for completeness?

**Comment by ocean90** [comment]
After save state is `$this`, isn't it?

**Comment by toolstack** [comment]
Yes... yes it is :wink:
