### ISSUE TITLE
Introduce an API for background processing

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress#336]
GlotPress has a few task which should run in a background processes. For example the propagation tasks or a possible upgrade routine for #311/#236.

A translator shouldn't have to wait for other tasks which are not his primarily action, which is in general just submitting one translation.

I recently found https://deliciousbrains.com/background-processing-wordpress/ which [provides two classes](https://github.com/A5hleyRich/wp-background-processing/tree/master/classes), `WP_Async_Request` and `WP_Background_Process`. Something similar would be good base to allow GlotPress (and plugins) to manage processes which are triggered by user interactions but shouldn't block their primarily flow.

Note: `WP_Async_Request` uses admin-ajax.php, I'd like to try this with a REST API endpoint.

**Comment by toolstack** [comment]
Looks interesting.  Obviously there would be concerns around making sure the background processes don't get stuck.

The REST API seems to be in flux still so I'm not sure that would be a good idea yet.

I wonder how much of this could be accomplished with hooking in to the shutdown action instead so we don't impact the user experience but don't have to build an async system.

**Comment by ocean90** [comment]
> The REST API seems to be in flux still so I'm not sure that would be a good idea yet.

Not sure why you think that, but the infrastructure is already part of the core. If it's about the endpoints for posts/users/etc, that's not really important for custom routes.

> I wonder how much of this could be accomplished with hooking in to the shutdown action instead

Shutdown function are part of the process, so it still blocks further actions/rendering.

``` php
<?php
function shutdown() {
    sleep(2);
}
register_shutdown_function( 'shutdown' );

echo "Hi!\n";
```

``` bash
$ time php -f shutdown.php
Hi!
php -f shutdown.php  0,01s user 0,01s system 0% cpu 2,027 total
```

**Comment by toolstack** [comment]
I haven't been following the REST API too closely, I've just seen some ongoing discussion about how to get it in to core.  If that's just the endpoints, then we should be fine to use it.

Yes, but shutdown executes after all html is rendered, so it doesn't block the page display, it just has a longer execution time.

**Comment by ocean90** [comment]
> it just has a longer execution time.

Which would be bad for XHR requests.

**Comment by ocean90** [comment]
Closing as _maybelater_.
