### ISSUE TITLE
Translation Sets: A failed update redirects to /sets/-new

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress#349]
Steps to reproduce:
1. Create a new translation set
2. Go to the edit page of that set
3. Clear the locale value
4. (Clear the name field)
5. Click Save

Expected: You stay on the edit page.
Actual: You're at /sets/-new.

**Comment by toolstack** [comment]
PR #331 solves that by using the locale name for the name field if it is blank.

More interestingly though is another issue, when you edit the set the Locale isn't selected correctly as the option value has "checked" instead of "selected" used.

**Comment by ocean90** [comment]
@toolstack Not it doesn't, that's why I created this issue. :)

**Comment by toolstack** [comment]
Works on my install correctly, let me double check.

The other issue is because the on line 243 of template.php `checked()` is used instead of `selected()`.

**Comment by ocean90** [comment]
@toolstack Updated the steps to reproduce.

**Comment by toolstack** [comment]
Ah, got it now.
