### ISSUE TITLE
Database is only updated on plugin activation

### ISSUE THREAD

**Issue by toolstack** [GlotPress/GlotPress#35]
The current database update code is contained in the plugin activation hook, however this hook is not fired when a plugin upgrade occurs.

This code should be moved outside of the activation function.

**Comment by bradt** [comment]
:+1:

**Comment by toolstack** [comment]
As per the discussion during the weekly meeting (https://wordpress.slack.com/archives/glotpress/p1444915779000075), the upgrade check should only be run on the admin pages.

Concerns with this are that if a user has enabled auto update of plugins new features may not be functional (or worse the plugin may fail) until the admin has visited the backend.  To mitigate this conditional code needs to be added to ensure no new features that require the update code to run are used until after it has run.

Running the upgrade process on every page load avoids this concern but does potentially has other side effects for the page load that it runs on (if there is a long upgrade process required the user of that page load may see a delay in loading or a complete failure or error message).

Both have pros and cons and running only during admin page loads received the most votes during the meeting.
