### ISSUE TITLE
Move locales.php into a separate repo

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress#350]
Proposal:
- Move locales/locales.php to a repo at glotpress/locales
- Include glotpress/locales as a submodule for this plugin

Why? To separate the flow of adding new locales from the plugin. For example we can use templates (https://github.com/blog/2111-issue-and-pull-request-templates). It makes it also easier to use for other projects which don't need the whole GlotPress, just the list of locales.

We can and should also try to make some of the pre-checks, like valid ISO codes or locale names, automated via Travis CI.

**Comment by toolstack** [comment]
We should probably even go farther than that and allow a site to update their locales independently of GlotPress.

I agree it should be it's own repo and a submodule to GlotPress-WP, but beyond that:
- There should be an admin interface to pull a new copy of the locales from the repo and update GP.
- Maybe create a new table to hold the locales so that individual sites can add their own custom ones wihout losing them on each upgrade (or not getting new locales if they've used their own locales.php).

**Comment by ocean90** [comment]
`locales.php` is a drop-in and can be replaced. So it can also replaced with a file which uses a db table for the locales, it just needs to implement the public methods like by_field() or locales().

**Comment by ocean90** [comment]
Example: https://github.com/ocean90/gp-locales/commits/develop/locales.php

``` bash
$ git clone git@github.com:ocean90/GlotPress-WP.git
$ cd GlotPress-WP
$ git filter-branch --prune-empty --subdirectory-filter locales develop
$ git remote set-url origin git@github.com:ocean90/gp-locales.git
$ git push origin HEAD
```

Based on https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/.

**Comment by toolstack** [comment]
I'm thinking we need to take a closer look at how the locales are managed, #385 is a good example where we probably need some more rigor around how locales are changed.

I think we need to separate the class from the data and build out the class to handle adding, updating and deleting locales, probably as data in a table.

**Comment by ocean90** [comment]
There is https://github.com/GlotPress/gp-locales now. The is only one issue with a separate repo: It's not possible to include just one file as a submodule. Not sure if it's a good idea to include all the upcoming tests and readmes too.

**Comment by ocean90** [comment]
> Not sure if it's a good idea to include all the upcoming tests and readmes too.

We could add them to https://github.com/GlotPress/GlotPress-WP/blob/develop/bin/release.ini#L21

**Comment by ocean90** [comment]
Closing as a wontfix for now.
