### ISSUE TITLE
Don't call gp_upgrade_data() in gp_upgrade_db() on install

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress#361]
If `gp_upgrade_db()` runs for the first time `gp_upgrade_data()` gets called with `false` for the `$db_version` parameter, thus the query for `$db_version < 190` runs.
- [x] Don't call `gp_upgrade_data()` if `get_option( 'gp_db_version' )` returns false
- [x] Remove the unused global import for `$wpdb;` from `gp_upgrade_db()`
- [x] Remove the `$db_version < 190` query since this will never run. The default version for all installs is `940`.

**Comment by toolstack** [comment]
It will run in the case of a first install (false=0) but of course there will be no data to upgrade in that case.

Since it's not used should we just remove the entire `gp_upgrade_data()` function and call?

**Comment by ocean90** [comment]
No need to remove it if we're going to use it sooner or later. For example for #293.

**Comment by toolstack** [comment]
#293 won't need `gp_upgrade_db()` as it will probably just add columns to the database which will be handled by `dbDelta()`.
