### ISSUE TITLE
Show all translation warnings at once

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress#370]
Currently only the first warning is shown, means the user can't adjust their translation at once or a validator has to reject each warning separated.

![glotpress-warnings](https://cloud.githubusercontent.com/assets/617637/14043009/e5c52b02-f27f-11e5-90fa-b5ef1e41cc5f.gif)

**Comment by Mte90** [comment]
Uuuh very interesting will help also on glotdict :-D
