### ISSUE TITLE
Bump version for scripts

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress#374]
After #355 and #371 we should bump the version in https://github.com/GlotPress/GlotPress-WP/blob/0e3826646756b542c1c44566c9cb8d0494f2f13e/gp-includes/assets-loader.php#L27 to avoid cache issues.

Should we use `GP_VERSION` instead?

**Comment by toolstack** [comment]
`GP_VERSION` probably isn't a good choice as that would bust the cache unnecessarily on every release.

Perhaps just defining a `GP_SCIPTS_VERSION` and updating that when we change the scripts might be a trade off.  We still bust the cache for some scripts that don't need to be updated when we make a change to another script, but at least when we're doing hotfixes we don't invalidate the cache unnecessarily.
