### ISSUE TITLE
Allow to translations to be imported with status waiting

### ISSUE THREAD

**Issue by akirk** [GlotPress/GlotPress#377]
In certain environments like translate.wordpress.org it can make sense to allow some people to only import translations with the status "waiting".

This can be established by creating a new `import-waiting` permission, as well as adding a dropdown to select the status for imported translations.

Mockup:
<img width="332" alt="glotpress-import-waiting-current" src="https://cloud.githubusercontent.com/assets/203408/14179555/cbe7c3ae-f75f-11e5-98d7-15dcbe485135.png">

**Comment by toolstack** [comment]
I think the logic is a little backwards on this, `import-waiting` as you've done it is effectively a negative permission (by having it you lose access to import current) which is the wrong way to do it.

It might make more sense to have two separate rights, which both grant access to the import type, like `import-waiting` and `import-current`.  A user with each of those rights would be able to import that type of status.

I have a few other comments but they're specific to the PR so I'll add them there.

**Comment by ocean90** [comment]
> This can be established by creating a new `import-waiting` permission, 

Both - `import-waiting` and `import` - permissions will prevent existing validators to upload translations. How can we prevent that? Can we map both to `approve`? Note that the current permission system doesn't support _removing_ a permission (via the UI), so it wouldn't be possible to have a user which can approve but not import.

**Comment by toolstack** [comment]
There are a couple things we could do to handle the current users (and by the way I'm not convinced this is a change that belongs in core yet):
- As part of the upgrade process, add `import` permissions to anyone that currently has `approve`.
- Add in to the permissions check for `import`, `import-waiting` and `approve`
