### ISSUE TITLE
"Use as name" on translation set creation page does not work

### ISSUE THREAD

**Issue by toolstack** [GlotPress/GlotPress#381]
Create a new translation set, select a locale and then click "Use as name" and the name field is not populated.

The javascript that does the work is wrapped in an anonymous jQuery function that does not seem to be working any more.

**Comment by ocean90** [comment]
Seems to work in Chrome, which browser are you using?

**Comment by toolstack** [comment]
I tried it in Edge, IE and Firefox, failed on all of them.
