### ISSUE TITLE
"Not found" error when attempting to view and edit sub-projects

### ISSUE THREAD

**Issue by goblindegook** [GlotPress/GlotPress#388]
We have GlotPress 2.0 running on a secondary site in a multisite instance, and GlotPress throws a "Not found" error when attempting to view or edit a sub-project. We've tried multiple permalink settings, with and without a trailing slash, but no luck.

GlotPress version: 2.0
WordPress version: 4.4.2
Configuration: directory-based multisite, HTTPS

**Comment by toolstack** [comment]
What url is it generating for the view/edit link?  ie. http://domain.com/glotpress/projects/parent/child

**Comment by ocean90** [comment]
This seems be related to #265. @goblindegook can you check in the database if the value in the `path` column has a trailing slash?

**Comment by goblindegook** [comment]
@toolstack: Here are our URLs and the current permalink settings:
- URL for viewing: `https://<hostname>/i18n/glotpress/projects/<project-slug>/<subproject-slug>`
- URL for editing: `https://<hostname>/i18n/glotpress/projects/<project-slug>/<subproject-slug>/-edit`
- Current permalink settings: `/%year%/%monthnum%/%day%/%postname%`

@ocean90: The path does indeed have a trailing slash, and it seems to be the problem. I removed it from the affected entries and the subprojects are now accessible. New subprojects are created without the trailing slash too, only the subprojects created under version 1.0 seem to not have been migrated.

Thanks!

**Comment by ocean90** [comment]
Thanks @goblindegook!

Moving to 2.0.1 and thinking about an upgrade routine which removes the trailing slash for project paths.
