### ISSUE TITLE
Wrong permission for delete actions

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress#389]
- https://github.com/GlotPress/GlotPress-WP/blob/2.0.0/gp-includes/template-links.php#L107, should be `delete`
- https://github.com/GlotPress/GlotPress-WP/blob/2.0.0/gp-includes/template-links.php#L175, should be `delete`
- https://github.com/GlotPress/GlotPress-WP/blob/2.0.0/gp-includes/routes/translation-set.php#L120, should use another helper, `cannot_delete_set_and_redirect()`, or https://github.com/GlotPress/GlotPress-WP/blob/2.0.0/gp-includes/routes/translation-set.php#L148

**Comment by toolstack** [comment]
Additional [discussion on Slack](https://wordpress.slack.com/archives/glotpress/p1460406873001321).
