### ISSUE TITLE
Allow modification of accepted HTTP methods in the router

### ISSUE THREAD

**Issue by yoavf** [GlotPress/GlotPress#393]
Use case: a GP plugin that allows Cross-Origin requests. Chrome precedes this with an HTTP OPTIONS request, which is currently filtered by the whitelist of http methods.

**Comment by toolstack** [comment]
Could you provide a real life example of this?  Do you have a plugin in mind you want to write that requires this?

**Comment by yoavf** [comment]
Sure - On WordPress.com (both the site itself, and all of our users sites), we run a tool called the community translator. It provides a front end interface to GlotPress. As logged in users to WordPress.com are already logged in to translate.glotpress.com (our GW install, soon to be using the plugin version) they can submit translations of WordPress.com or their theme using that tool. 

( The Community Translator communicates with some custom endpoints in our GP install, see https://github.com/Automattic/gp-extended-api-plugins/blob/rewrite/translations-wordpress-plugin/gp-translation-extended-api/gp-translation-extended-api.php )

However, since some of these requests originate from different domains, we need to enable cross-site requests. To do that, we do the following:
- Enable OPTIONS in the router (this issue/PR)
- In a separate plugin, we add `Access-Control-Allow-Origin` and `Access-Control-Allow-Credentials: true` headers in `gp_before_request`, after we have verified that the request did in fact originates from one of our whitelisted domains

**Comment by toolstack** [comment]
Thanks.

I'm not sure it would make sense to have this in core, but I could certainly see supporting a filter for the array of http methods to let a plugin alter it.

So instead of:

```
foreach ( array( 'get', 'post', 'head', 'put', 'delete', 'options' ) as $http_method ) { 
```

have:

```
$http_methods = apply_filters( 'gp_router_http_methods', array( 'get', 'post', 'head', 'put', 'delete', 'options' ) );

            foreach ( $http_methods as $http_method ) { 
```

**Comment by yoavf** [comment]
@toolstack Thanks - updated the PR

**Comment by ocean90** [comment]
This will probably be superseded by #338, but since there is no progress yet I'm fine with a filter for the meantime.

**Comment by toolstack** [comment]
The updated PR looks good.
