### ISSUE TITLE
Export - allow optional deep export from project and child projects

### ISSUE THREAD

**Issue by yoavf** [GlotPress/GlotPress#407]
When exporting, it might be useful to also export from child projects as well, so that all originals and translations are exported to one unique file.

**Comment by toolstack** [comment]
I don't see how that would be very useful, how would you handle duplicate strings with different translations?

This might be better as a plugin than in core.

**Comment by yoavf** [comment]
Revisited why we implemented this on wpcom, and this scenario is no longer relevant for us, nor it makes much sense for anyone else
