### ISSUE TITLE
Using utf8mb4 chars as names/slugs of projects can't be found

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress#415]
Steps to reproduce:
- Have a database which supports utf8mb4 encoding
- Create a project with 🌍 as the title

**Comment by toolstack** [comment]
I noticed this when I was working on #410.

**Comment by garretthyder** [comment]
Reopening as PR #934 broke the Glossary entry form as it contained the '//' prefix workaround. Will have a fix for this shortly.

For reference when on the Glossary entry form the $project_or_path supplied to gp_url_project is '//languages' which when urlencoded becomes %2F%2Flanguages causing it to be overlooked in the following checks as well as making it an invalid URL. 
Upon submitted you get a Not Found;
![screen shot 2018-10-30 at 3 05 22 pm](https://user-images.githubusercontent.com/8726005/47754190-4c968b00-dc57-11e8-9a6d-430c01c35892.png)
