### ISSUE TITLE
Add header "Language" to metadata  .po

### ISSUE THREAD

**Issue by yuretzru** [GlotPress/GlotPress#428]
Exported po-files incompatible with some libraries.
meta Language needed.
You can easy fix it.

file:
gp-includes/formats/format_pomo.php

add at line: 20
`$po->set_header( 'Language', $locale->lang_code_iso_639_1 );
` 

result:

```
        $po->set_header( 'Content-Transfer-Encoding', '8bit' );
        $po->set_header( 'Plural-Forms', "nplurals=$locale->nplurals; plural=$locale->plural_expression;" );
        $po->set_header( 'X-Generator', 'GlotPress/' . GP_VERSION );
        $po->set_header( 'Language', $locale->lang_code_iso_639_1 );  // new line !!!

        // force export only current translations
        $filters = array();

```

**Comment by ocean90** [comment]
Thanks for the report @yuretzru!

GNU gettext specification: https://www.gnu.org/savannah-checkouts/gnu/gettext/manual/html_node/Header-Entry.html

Some locales don't have an ISO 639 1 code but based on https://www.gnu.org/savannah-checkouts/gnu/gettext/manual/html_node/Language-Codes.html#Language-Codes three letter codes are supported as well.

**Comment by yuretzru** [comment]
Hi Dominik!
You are right, my code is incorrect.
But the tag "Language" is very necessary for me :)
Culd you add it?

**Comment by toolstack** [comment]
@yuretzru grab this [format_pomo.php](https://github.com/GlotPress/GlotPress-WP/blob/428-add-language-header-to-po-exports/gp-includes/formats/format_pomo.php) and see if it does what you need.

**Comment by yuretzru** [comment]
Yes!!!
Thank you Greg!!!!!
