### ISSUE TITLE
Update release.ini to remove CHANGELOG.md and codecov.yml.

### ISSUE THREAD

**Issue by toolstack** [GlotPress/GlotPress#433]
codecov.yml has been added to the repo so the release script should delete it when pushing to w.org.

Also CHANGELOG.md was missed during the initial setup of the release script and should be deleted as well as it is appended on to the readme.txt file.

**Comment by ocean90** [comment]
I don't think that we should remove CHANGELOG.md. The size of the readme.txt is limited on w.org so at some point we have to remove some entries from the readme.txt and linkt to CHANGELOG.md for the full changelog.

**Comment by toolstack** [comment]
You don't have to remove the entries from readme.txt as w.org just drops off the last ones when the size limit is hit and it displays everything up to that point.  The file itself doesn't seem to have a limit, just what w.org displays.

**Comment by toolstack** [comment]
As per [discussion in Slack](https://wordpress.slack.com/archives/glotpress/p1463507183000704), we'll leave CHANGELOG.md and just remove codecov.yml.
