### ISSUE TITLE
Deprecation policy

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress#453]
We should have a deprecation policy which documents when deprecated stuff gets finally removed. Something like:

x: Add a deprecation notice.
x + 1: Continue showing a deprecation notice.
x + 2: Remove deprecated code.

Related: #452

**Comment by toolstack** [comment]
I agree, though it might get tricky depending on the release schedule.

Assuming x in the above is a major release (aka 2.0 or 3.0) that could be a long time before the code is actually removed.  Perhaps if we let deprecation happen in a point release that might make it a little more streamlined.

For example:
- Deprecate the GP CLI in 2.1
- Show notices in 2.2, 2.3, 3.0, 3.1, .etc.
- Remove in 4.0

Perhaps use the rule that deprecation notices must be shown in at least one major release before the code is removed.  That would allow for deprecating in say 3.0 and removal in 4.0.

**Comment by toolstack** [comment]
See [draft policy](https://github.com/GlotPress/GlotPress-WP/wiki/7.-Deprecation-Policy).

**Comment by ocean90** [comment]
Thanks @toolstack, removed the draft hint from the page.
