### ISSUE TITLE
Schema: Define max index length for `user_id_action`

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress#462]
See https://wordpress.slack.com/archives/glotpress/p1465028403001050.

`KEY user_id_action (user_id,action)` 
should be
`KEY user_id_action (user_id,action($max_index_length))`

**Comment by toolstack** [comment]
Do we want to limit the index length or reduce the action size?

The action size is probably too long in the database and just wastes space.

**Comment by ocean90** [comment]
That may work too. We're doing this in https://github.com/GlotPress/GlotPress-WP/blob/cbf2ba65f01dba812ee9f5ab96fffa1828758f43/gp-includes/schema.php#L152 too (which doesn't seem to be right...)

**Comment by ocean90** [comment]
`project_id_status` might be another case: https://github.com/GlotPress/GlotPress-WP/blob/cbf2ba65f01dba812ee9f5ab96fffa1828758f43/gp-includes/schema.php#L96

**Comment by toolstack** [comment]
Definitely not right, as an index could still be too big by combining multiple columns together.
