### ISSUE TITLE
Android exports: translation can't start with a @

### ISSUE THREAD

**Issue by maxme** [GlotPress/GlotPress#469]
When a translation starts with a `@` character, it must be backslashed in Android exports. Android use strings starting by `@` for referencing other strings.

Sample exported by GlotPress:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="test">@fail</string>
<resources>
```

But should be:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="test">\@fail</string>
<resources>
```

**Comment by toolstack** [comment]
Do you have a link to the documentation for how to handle the @?

**Comment by maxme** [comment]
@toolstack [Here](https://developer.android.com/guide/topics/resources/string-resource.html) and [there](https://developer.android.com/guide/topics/resources/string-resource.html#FormattingAndStyling). The `@` starting a string is not forbidden, but it's used to reference other strings in Android.

Citing the doc:

> resource reference:
>     In Java: R.string.string_name
>     In XML:@string/string_name 

For instance we use references for untranslatable strings in our app, [here](https://github.com/wordpress-mobile/WordPress-Android/blob/30b7d42e81d7b8363dea54495d165ab20c606ee5/WordPress/src/main/res/values/strings.xml#L938-L949). But it doesn't make sense to "translate" these identifiers, so GP should assume translations are not references and should not start by a `@`.

**Comment by maxme** [comment]
Also note the following example is correct and doesn't need to be backslashed:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="test">see you @ the beach</string>
<resources>
```

**Comment by toolstack** [comment]
Would there by any case where it should be assumed a translation starting with an @ should not be escaped?

If we escape any translation that starts with an @ then there is no way to make it a reference to another string.

**Comment by maxme** [comment]
We could eventually escape only strings that starts by `@` but does not match `@[a-z_]+/[a-z_]+` (reference format).

IMO, that's a bit risky to have references in the translations: if a translator change  a reference (e.g.  `@string/hello` to `@chaine/salut`) that could lead to a crash in the app. It's probably safer to have all references escaped.

Note: that's why all string references are marked `untranslatable` in our Android project.

**Comment by toolstack** [comment]
Ok, sounds reasonable, I've created a PR for this so it should be in the next release.

**Comment by maxme** [comment]
Thanks a lot @toolstack!
