### ISSUE TITLE
Uncaught ReferenceError: $gp_translations_options is not defined

### ISSUE THREAD

**Issue by Stiofan** [GlotPress/GlotPress#476]
$gp_translations_options is not being added to the page via wp_localize_script() from translations.php template.  I am running multi-site so not sure if that is why its showing or if everyone else is seeing it also.

Basically it needs to be wrapped in a function and called via the wp_enqueue_scripts hook.

I will try submitting a patch if i can get my head around the process.

**Comment by toolstack** [comment]
It seems to be working alright on my local install (single site).

It shouldn't need to be called via wp_enqueue_script as it's being written before the html headers are complete.

It may be related to how we add the scripts in `gp-includes\assets-loader.php` as we directly act on the `WP_Scripts` object though the `wp_default_scripts` hook.

**Comment by ocean90** [comment]
For some reasons I get this only when I'm logged out (single site).

**Comment by toolstack** [comment]
I can replicate @ocean90's behaviour.

**Comment by Stiofan** [comment]
My issue with it while logged in was due to a old version of this plugin being network activated https://wpgeodirectory.com/translate/glotpress/projects/geodirectory/sv/default/

I can see the issue with logged out users too.

**Comment by Stiofan** [comment]
Updated pull request, seems to fix for all, feedback welcome.

**Comment by toolstack** [comment]
This problem goes deeper than just wrapped in a function, it's caused by GP adding the translations page js file on every page instead of just the translation page.  There are a few other js files loaded on pages where they aren't required as well.

**Comment by toolstack** [comment]
@NomadDevs can you try [this code](https://github.com/GlotPress/GlotPress-WP/pull/497) and make sure it resolves the issue you are seeing?

**Comment by Stiofan** [comment]
@toolstack That code did not work for me, it does not display any JS errors but it breaks all the JS functionality of opening translations etc, it removed the localize script for me.

**Comment by toolstack** [comment]
@NomadDevs Give it a try now.

**Comment by Stiofan** [comment]
@toolstack With what version of GP?

**Comment by toolstack** [comment]
I updated the PR, so just grab the code from the same spot.

**Comment by toolstack** [comment]
@NomadDevs try [this code](https://github.com/GlotPress/GlotPress-WP/pull/500) instead and see if it works for you.

Note: If your using my "GP Single Click Edit" plugin you'll need to disable it to test with.

**Comment by Stiofan** [comment]
@toolstack Yes your latest code seems to resolve all issues.

**Comment by toolstack** [comment]
Good to hear.

**Comment by toolstack** [comment]
Resolved with PR #500.
