### ISSUE TITLE
Issues with v2.1.0 Beta 1 release

### ISSUE THREAD

**Issue by deckerweb** [GlotPress/GlotPress#487]
Hi there!

I caught some issues and try to explain here a bit:
- after upgrade from 2.0.1 to 2.1.0 beta 1 the translations editor did skip one item after saving the current item
- as far as I could tell, the "saved" item was not really saved (see below downgrading)
- the first import of originals for a new project is not faster yet than with 2.0.1
- when importing existing translations to a project all translations had the status "Waiting" --> when approving them, they didn't changed to "Approved" status

Since my private GlotPress install is a "production install" for my work & business I need it daily so I had to downgrade to stable 2.0.1 again, sadly.
- after that all worked as expected again
- the "saved" translations during 2.1.0 beta 1 were not there then, I had to translate again

_Further on, 2 things, very important for me:_
1) status "Waiting" after importing a translation file makes no sense: I often translate big plugins with hundreds or even thousands of strings, to approve hundreds of strings manually every time feels totally senseless --> therefore it should better be the current behavior ("Approved" status), or just make a user setting which status is wanted for import!!!

2) more performance improvements in any way for importing originals would be awesome! Maybe for all other tasks as well, but importing originals seems the most needed from my experience with the plugin version

Thanks for your hard work!
So far the plugin version really rocks! :-)

**Comment by toolstack** [comment]
What web browser are you using?

It sounds like something has gone wrong with the JavaScript on the translation page.

As for the importing, if your an admin/approver you can select current or waiting for imports, but if you are only a "standard" user it will only allow for waiting.

**Comment by deckerweb** [comment]
- Browser: I use Firefox (latest version) as primary browser on OS X (latest version)
- JavaScript: I will make another update and testing tonight and see if I can find any JS errors etc.
- Imports: the WP install only has 1 user, that's me as admin, also GlotPress user rights are set to administrator in user profile --> but as written above it was importing into "waiting" status in v2.1.0 beta 1

I will report back from the 2nd testing tonight

**Comment by deckerweb** [comment]
Another idea, could the translation propagation be causing the slow performance maybe?

**Comment by toolstack** [comment]
When you test make sure you flush your firefox cache so the JavaScript files get the right versions.

Do you use a custom template directory?  If so you need to make sure to update the import template with the changes from the default templates.

Are you using the propagation plugin?  If so, yes, it does have a significant impact on importing.

**Comment by ocean90** [comment]
@deckerweb Do you have any news for us? Happy to help with debugging if you didn't find the cause yet.

**Comment by deckerweb** [comment]
@ocean90 & @toolstack 
Hi there!
Sorry for the delay, today I did another round of testing, and all works now as it should!

My fault in first attempt was, that I did forget the templates.
As I use a modified header & footer, I use a custom folder for all template files. Now I did update also these templates and all worked as expected, nothing of the issues above occurred! :)

I am sorry, but thanks to @toolstack for the mention of templates! Since I made a diff with all templates it was logical I had issues, regarding all the changes... :)

Also testing another bigger import files for originals: this is really faster now, and I mean you can "feel" it, so thanks a lot for the improving here!
- a theme with 500 strings + a plugin with about 2.000 strings: originals did import really fast in both cases, as compared to v2.0.1 --- and in both cases the "Auto Propagation" plugin was active!

I'll let 2.1.0 Beta 1 installed in my (production) environment. So far all is stable. May I find other issues I may report here.

So thanks again for your hard work, support and patience!
-Dave :)

**Comment by toolstack** [comment]
Thanks @deckerweb, glad its working for you.
