### ISSUE TITLE
Replace use of `GP_User` with `WP_User` and associated WP functions

### ISSUE THREAD

**Issue by bradt** [GlotPress/GlotPress#5]

**Comment by bradt** [comment]
@gilbitron Already took a chunk out of this with beb4920850ceff5c7c7e0b0308b66c1293283ade.

**Comment by A5hleyRich** [comment]
Work on this continued in #19, as PRs overlap.

**Comment by bradt** [comment]
.@ocean90 is working on a solution to #19 that may take care of this. If it doesn't pan out though, we should reopen #20.
