### ISSUE TITLE
Support minified version of the JavaScript files.

### ISSUE THREAD

**Issue by toolstack** [GlotPress/GlotPress#505]
Currently GP's JavaScript files (except the tablesorter) are unminified, we should minify them and support the `SCRIPT_DEBUG` flag in WordPress.

**Comment by ocean90** [comment]
As mentioned in #17 minification of assets should be done automatically either with grunt or gulp. Also, minified files shouldn't be under version control IMO.

**Comment by toolstack** [comment]
The minified files should be under version control so we can push the release to wordpress.org properly as well as do testing with both version of the files.

Otherwise we'd have to build the minified files during the release process and have no testing before the release.

Not having them under version control also means that to use the development version of GP you must have `SCRIPT_DEBUG` enabled.

I think the benfits of having them in version control outweigh the drawbacks.
