### ISSUE TITLE
Introduce a warning for incorrect quotes in links

### ISSUE THREAD

**Issue by SergeyBiryukov** [GlotPress/GlotPress#511]
There should be a warning if quotes in links or other HTML attributes are translated incorrectly (e.g. to fancy quotes instead of regular double quotes), see https://core.trac.wordpress.org/ticket/37367.

**Comment by ocean90** [comment]
We already have a warning if the HTML is invalid/missing:
<img width="581" alt="" src="https://cloud.githubusercontent.com/assets/617637/16852384/2f1baf4e-4a08-11e6-8f2a-c08d022efe71.png">
