### ISSUE TITLE
Convert "Wordpress" to "WordPress" on saving

### ISSUE THREAD

**Issue by SergeyBiryukov** [GlotPress/GlotPress#515]
As [reported by @wolly66 and confirmed by @Presskopp](https://wordpress.slack.com/archives/polyglots/p1468866750000038), there are [3 old strings](https://translate.wordpress.org/projects/wp/4.5.x/admin/it/default?filters%5Bterm%5D=Wordpress&filters%5Buser_login%5D=&filters%5Bstatus%5D=either&filters%5Bcase_sensitive%5D=yes&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc) in Italian translation that look proper in GlotPress (with "WordPress" capitalized correctly), but not on an actual install (with a lowercase "p" in "WordPress").

GlotPress could probably use `capital_P_dangit()` on saving to make sure "WordPress" is always capitalized correctly in new translations.

**Comment by ocean90** [comment]
This can and should be handled in a custom plugin. GlotPress is not only used for WordPress translations. But if we need a filter to customize translations before they are stored, that can be added.

**Comment by SergeyBiryukov** [comment]
`capital_P_dangit()` has an ambitious description — `Forever eliminate "Wordpress" from the planet (or at least the little bit we can influence)` — so I thought it might be useful even for non-WordPress projects (if they occasionally use "WordPress" in a string, make sure they capitalize it correctly, as they are generally less likely to care about that).

I agree though, it can be a custom plugin.

**Comment by SergeyBiryukov** [comment]
Follow-up: https://meta.trac.wordpress.org/ticket/1853
