### ISSUE TITLE
Introduce a filter to customize translations before saving

### ISSUE THREAD

**Issue by SergeyBiryukov** [GlotPress/GlotPress#517]
It would be helpful to have a filter for performing some corrections on translations before they are stored in the database (see #515 for an example use case).

It's currently possible to customize translations after saving using the `'gp_translation_saved'` action, but that's a workaround leading to an additional SQL query.

Would `GP_Translation::prepare_fields_for_save()` be the most appropriate place for a filter like that?

**Comment by toolstack** [comment]
Seems like a reasonable place to put it.
