### ISSUE TITLE
"missing text" is not displayed in translation set view

### ISSUE THREAD

**Issue by yoavf** [GlotPress/GlotPress#519]
Example:
![wporg examle](https://cloud.githubusercontent.com/assets/844866/17211754/ee539900-54d3-11e6-948f-fe13ff5fb145.png)

This probably happens since https://github.com/GlotPress/GlotPress-WP/commit/7b103dd555979a22e27b35fe5cb44bb6b28411dc - where the array of translations supplied by `for_translation()` is filtered with `gp_is_not_empty_string()` 

Non translated entries will have an array with two null values. `gp_is_not_empty_string` returns true for them. A possible solution would be to amend it to 

```
function gp_is_not_empty_string( $value ) {
    return is_string( $value ) && '' !== $value;
}
```

... but then the function name would not be semantically correct. Maybe we can rename it to `gp_is_string_not_empty`

**Comment by ocean90** [comment]
@yoavf See #560, instead of using a check for strings we can simply check if the value is `null`.
