### ISSUE TITLE
Possibility to automatically import / export language files

### ISSUE THREAD

**Issue by Ninos** [GlotPress/GlotPress#521]
Hey there,
is it possible to automatically import / export language files? E.g.:
- Git code is updated -> import new .pot-file into gp (sync)
- Git tag was added -> CI want to download all translated languages from gp (e.g. creation of archive)

ATM I seems that I need to do that on user level. May adding the possibility to handle such things via API + general token(s) defined in admin panel would enhance such processes.. :)

**Comment by toolstack** [comment]
You can use my [Auto Extract plugin](https://wordpress.org/plugins/gp-auto-extract/) to help automate the process but it isn't triggered by GitHub, it is still kicked off by a user.

Likewise you can use my [Bulk Download plugin](https://wordpress.org/plugins/gp-bulk-download-translations/) to simplify downloading the translations.

There is a CLI for importing originals and there is a ticket open ([#338](https://github.com/GlotPress/GlotPress-WP/issues/338)) to look at using the REST API.

It would seem unlikely that this kind of functionality would be brought in to the core of GlotPress as extracting originals from source code is dependent on the type of source code your using (PHP is obviously used for WordPress, but GlotPress isn't limited to PHP, it can be used for any language that supports get-text).

**Comment by Ninos** [comment]
Cool thx for feedback! About the last functionality I also think this is not a task which has to be done by GlotPress. For me it would be fine to have such REST API for importing my generated .pot-files :)

**Comment by ocean90** [comment]
Closing as wontfix due to reasons noted above.

**Comment by helgatheviking** [comment]
I know this is eons old now, but I was thinking about it today:

>Git code is updated -> import new .pot-file into gp

a REST API endpoint that you could send a .pot file too (or just the URL) would be very handy given my current plugin build process. There's already a CLI command that's similar so could that be borrowed/repurposed?
