### ISSUE TITLE
GP_Test_Template_Functions::test_gp_breadcrumb_should_run_empty_string_through_filter_without_params() is failing

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress#528]
See https://travis-ci.org/GlotPress/GlotPress-WP/jobs/157454271#L235.

**Comment by toolstack** [comment]
Related to #471?

**Comment by toolstack** [comment]
I've been able to reproduce this issue on my local install, it's related to PHPUnit 5.5.2 (and 5.5.4, the current release has the same behaviour) being used for PHP 7 and the `getMock()` deprecation.

Using PHPUnit 4.8.15 with PHP7 doesn't produce the problem (though it does produce others).

I think fixing #471 will resolve this as well.

**Comment by toolstack** [comment]
I've been able to reproduce this issue on my local install, it's related to PHPUnit 5.5.2 (and 5.5.4, the current release has the same behaviour) being used for PHP 7 and the `getMock()` deprecation.

Using PHPUnit 4.8.15 with PHP7 doesn't produce the problem (though it does produce others).

I think fixing #471 will resolve this as well.

**Comment by toolstack** [comment]
I've been able to reproduce this issue on my local install, it's related to PHPUnit 5.5.2 (and 5.5.4, the current release has the same behaviour) being used for PHP 7 and the `getMock()` deprecation.

Using PHPUnit 4.8.15 with PHP7 doesn't produce the problem (though it does produce others).

I think fixing #471 will resolve this as well.

**Comment by toolstack** [comment]
Confirmed this is caused by the deprecated `getMock()` code, see PR #533 with the updated code that successfully passes the PHP7 tests.
