### ISSUE TITLE
Cancel link on projects/-new can have an empty href attribute

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress#547]
``` html
<p>
        <input type="submit" name="submit" value="Create" id="submit" />
        <span class="or-cancel">or <a href="">Cancel</a></span>
</p>
```

Notice the empty href attribute. This happens if `GP_URL_BASE` is `'/'` and the current permalink structure has no trailing slash.

**Comment by toolstack** [comment]
This is because `gp_url()` is the wrong function to use here, it only returns a relative portion of the url and what we really want is the GP root URL in this case.

We should use `gp_url_public_root()` instead.
