### ISSUE TITLE
Add keyboard shortcut for copying original string

### ISSUE THREAD

**Issue by GaryJones** [GlotPress/GlotPress#554]
Originally https://glotpress.trac.wordpress.org/ticket/98.

The `en_*` locales would really benefit from having a keyboard shortcut that copied the original string(s) and put focus into the input field for potential editing, and allowing the existing Shift-Enter keyboard shortcut to submit the string.

For `en_GB`, `en_AU`, `en_SA`, `en_CA`, and `en_NZ`, this would make translations in the ballpark of twice as quick. Those inputting strings for a locale where the original string is in a variation of that locale would also benefit (i.e. Informal German into Formal German etc. or some combinations of Spanish or Portuguese.)

The Trac ticket has a patch as a starting point.

**Comment by yayannabelle** [comment]
Not sure if entirely relevant, but it'd definitely make things more accessible, allowing a user to focus their hands solely on the keyboard, instead of going back and forth between mouse/keyboard, allowing for better efficiency, less energy used, and such.

Aka: Yes to all of the above! Please, great GlotPress gods, please bestow this feature upon us!

**Comment by ocean90** [comment]
Finding shortcuts which work for everyone is hard. The PR uses some which are already used by the OS.

What do you think about using something like https://craig.is/killing/mice which provides a simple API and also a plugin to record shortcuts so a user could define their own shortcuts for specific actions?

**Comment by toolstack** [comment]
The trade off is standardization vs customization, in this case I think standardization wins out, but that's my opionion.

Something like Mousetrap could simplify our keyboard handling but I'm not sure it's worth the extra library.  It could be worth a look though during the redesign for a more fulsome review of our keyboard interactions.

**Comment by ocean90** [comment]
I'm interested what other users think about this:

1) Are you using keyboard shortcuts?
2) What actions should have a shortcut?
3) Which keys should be used for shortcut? Should they be customizable?
4) Are you using any other services which provides keyboard shortcuts which you can recommend?

**Comment by ujdhesa** [comment]
1) Yes.
2) Copy, Paste, Save, Save As and similar.
3) The usual ones, used from OS interfaces. Customizable preferably.
4) Yes. Transifex, Poonton.

**Comment by glueckpress** [comment]
1) Yes.
2) Copy, paste, find (search), tabs to skip through the UI.
3) A shortcut to open/focus the text filter field would be awesome. Not sure about which keys should be used, maybe alt+ctrl+F? Customizing would be nice to have, but not required for initial feature imo.
4) The visual editor in WordPress has pretty useful shortcuts for headings and the like. Trello has some neat ones, and Slack.

**Comment by GaryJones** [comment]
1) Are you using keyboard shortcuts? _Yes_
2) What actions should have a shortcut? _Submit and Copy From Original to start with. Approve and Reject would also be useful._
3) Which keys should be used for shortcut? Should they be customizable? _If text fields are not selected, then single keys on their own, with no modifiers, may work well._
4) Are you using any other services which provides keyboard shortcuts which you can recommend? _GitHub :-) Hit `Shift-?` and the Show All to see all the shortcuts GitHub supports._

**Comment by Mte90** [comment]
GlotDict have different hotkeys maybe can be helpful :-) https://github.com/Mte90/GlotDict#hotkeys

**Comment by yayannabelle** [comment]
> 1) Are you using keyboard shortcuts?

Yep, shift + enter for saving translations.

> 2) What actions should have a shortcut?

Copying from Original, for sure! Approving/rejecting would be useful, but I'd prioritise the copying function over those.

> 3) Which keys should be used for shortcut? Should they be customisable?

As I don't use ctrl + arrow keys for their intended purposes (Mac user, hi), I'd be up for using some combination of them - I'd say ctrl + down arrow, as it'd feel like you're pulling the original translation down, making it easy to remember. (I can then re-map the shortcut for switching application windows in my settings, no worries.) That being said, having the shortcut be customisable would be very handy!!

> 4) Are you using any other services which provides keyboard shortcuts which you can recommend?

When using it previously, Notational Velocity had awesome shortcuts. GitHub as well! Atom's also pretty neat shortcut-wise.

**Comment by ntwb** [comment]
1) Yes
2) Copy original
3) CTRL-SHIFT-B
4) GlotDict https://github.com/Mte90/GlotDict#hotkeys

_This is from someone coming from the viewpoint of an English variant, copying from the original string is 95%+ of the actions performed for English variants_

**Comment by ePascalC** [comment]
Please get inspiration from GlotDict: https://github.com/Mte90/GlotDict#hotkeys
A way to easily define a set of actions as a user would be great of course! Like the CTRL+SHIFT+F in GlotDict that would check for a space in front of ':' and replace it with a non-breaking space.
