### ISSUE TITLE
Coding standard: Handle underscore in file names for formats

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress#568]
The WordPress coding standard doesn't allow underscores in file names. Our current `GP_Format` classes are violating this rule, see https://github.com/GlotPress/GlotPress-WP/tree/2.2.0/gp-includes/formats and https://travis-ci.org/GlotPress/GlotPress-WP/jobs/164555070#L229 for #567.

Option 1: Rename the files
Option 2: Exclude the gp-includes/formats directory from the specific rule.

``` xml
    <rule ref="WordPress.Files.FileName.UnderscoresNotAllowed">
        <exclude-pattern>*/gp-includes/formats/*</exclude-pattern>
    </rule>
```

**Comment by swissspidy** [comment]
I'd also move registering formats out of the class files, so the files only really contain the classes.

**Comment by toolstack** [comment]
@ocean90 I'd vote for option 1, just rename the files.

@swissspidy I wouldn't change how they're registered as 'things' are done the same way, seems to have been a design decision early on.
