### ISSUE TITLE
Something is wrong with exporting .mo when original string has msgid_plural and translation has only one msgstr

### ISSUE THREAD

**Issue by tg29359** [GlotPress/GlotPress#594]
See https://core.trac.wordpress.org/ticket/38620#comment:5.
The sample of the problem:
http://kabanenoimina.x0.com/223/#comments

**Comment by ocean90** [comment]
Confirmed.

Steps to reproduce:
- Create a new project
- Create a new translation set for JA
- Import originals, POT file: https://cloudup.com/c6gYPi3oUk0
- Import translations, PO file: https://translate.wordpress.org/projects/wp-themes/twentyseventeen/ja/default/export-translations
- Export MO file
- Try to convert the MO file back to PO: `msgunfmt twentyseventeen.mo -o twentyseventeen.po`

Expected: The command runs without errors and the PO file is complete.
Actual: There is an error `read-mo.c:249: invalid multibyte sequence` and some translations are missing in the PO file.

**Comment by ocean90** [comment]
Simpler test case:

``` php
<?php
require '/path/to/wp-includes/pomo/mo.php';

$mo = new MO();
$mo->add_entry( new Translation_Entry( [
    'singular' => 'Page Layout',
    'translations' => [
        '固定ページレイアウト',
    ]
] ) );

$mo->export_to_file( 'test.mo' );
```

`$ msgunfmt test.mo -o test.po` will produce the same error as above.

**Comment by ocean90** [comment]
Okay, that's a major issue and was introduced in 1a9e69548d5fc6fc0be6831846bf7cb603590b04.

Adding `$mo->set_header( 'Content-Type', 'text/plain; charset=UTF-8' );` to the test script generates a correct PO file.

MO files currently [don't have any headers](https://github.com/GlotPress/GlotPress-WP/blob/23ecb68906c6aebc82144390d7b335e056bb0ca2/gp-includes/formats/format-pomo.php#L113-L124) like the required `Content-Type` or `Plural-Forms`.

**Comment by toolstack** [comment]
Easy enough to fix, we can simply remove the override of the header output for mo's.
