### ISSUE TITLE
Migrate GlotPress standalone users and usermeta tables

### ISSUE THREAD

**Issue by bradt** [GlotPress/GlotPress#6]
As per #5, the plan is for the GlotPress plugin to no longer have a separate users and usermeta, but to use WordPress' tables as well as all the WordPress authentication awesomeness. If someone really doesn't want to mix their GlotPress users with the other users of their site, they can setup an independent WordPress install just for GlotPress.

GlotPress standalone can be setup to share a WordPress install's users and usermeta tables by defining the `CUSTOM_USER_TABLE` and `CUSTOM_USER_META_TABLE` constants. If that's the case for your GlotPress standalone install, then no migration is necessary.

If your standalone GlotPress install doesn't share the users and usermeta tables with a WordPress install, you will need to migrate the GlotPress users and usermeta table to the WordPress users and usermeta tables.

I propose that upon plugin activation, we detect if the GlotPress user and usermeta tables already exist and provide a dashboard-wide notice something to the effect...

> **Import GlotPress Users?** &mdash; We've detected users from a GlotPress standalone install. The GlotPress plugin no longer uses those tables. Would you like to import the users and their data into WordPress?
> [ Yes ] [ No ]

If they choose "No", we should permanently dismiss the notice. If they choose "Yes", we should take them to Tools > Import where they can choose to install a "GlotPress Users" plugin to carry out the import.

**Comment by gilbitron** [comment]
:+1:

**Comment by toolstack** [comment]
I don't know if this is even necessary, GP has never had a 1.0 release so anyone who's installed it can expect breaking changes and this could fall in to that category.  Especially since most people who would be interested in it probably already run GP using the WP users table :)

**Comment by JRGould** [comment]
This seems like functionality that should go into a plugin as it will probably be used/useful for only a short time after the GlotPress plugin is released. After that, it will mostly just be cruft that needs to be maintained indefinitely or have a committee vote to remove it.

**Comment by bradt** [comment]
Punted as per https://wordpress.slack.com/archives/glotpress/p1443706375001022.

**Comment by toolstack** [comment]
Closing as won't fix as we're well beyond this now :)
