### ISSUE TITLE
Don't store options in the meta table

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress#61]
Currently GlotPress stores options as `gp_option` in the meta table. We should replace this with the options API from WordPress.

**Proposal:**
- `gp_update_option()` => `update_option()`
- `gp_get_option()` => `get_option()`
- `gp_delete_option()` => `delete_option()`
- `gp_cache_all_options()` => Remove
- `gp_get_option_from_db()` => Remove
- `gp_option()` => Remove

**Comment by toolstack** [comment]
The only issue is with gp_get_option() as it does some funky stuff, it would have to be replaced with a mix of defines, get_option() and updating code (for the url=uri option for example).

**Comment by toolstack** [comment]
It turns out most of the 'funky' stuff wasn't actually used anywhere.

I've deleted it from the PR, in fact there are very few places the gp options code is used, the salt functions (which are being deleted in PR #69) are one of them so we'll have to be aware when the PR's are merged.
