### ISSUE TITLE
Unnecessary character in gp_radio_buttons()

### ISSUE THREAD

**Issue by Zodiac1978** [GlotPress/GlotPress#610]
![bildschirmfoto 2016-11-15 um 14 39 42](https://cloud.githubusercontent.com/assets/870475/20307847/a83745ec-ab41-11e6-89ac-cab714424424.png)

[This line](https://github.com/GlotPress/GlotPress-WP/blob/develop/gp-includes/template.php#L255) should be corrected to:
`		$res .= "\t<input type='radio' id='" . esc_attr( "{$name}[{$value}]" ) . "' name='" . esc_attr( $name ) . "' value='" . esc_attr( $value ) . "' $checked />&nbsp;";`

PR with all these branches is to complicated for me for this little bug ... sorry ;)

**Comment by toolstack** [comment]
The extra spaces aren't required, just the removal of the spurious single quote after `$checked`.

For your reference, PR's should be created against the develop branch.
