### ISSUE TITLE
Consider disabling the API by default

### ISSUE THREAD

**Issue by toolstack** [GlotPress/GlotPress#615]
Currently every install of GP has the GP API enabled on it, providing JSON data to applications that require it.  GP itself does not use it and runs fine without it.

Sites like translate.wodpress.org use this functionality, but more than likely most standalone sites may not.

So the question is should we disable the API default and allow it to be enabled on a per site basis?

**Comment by toolstack** [comment]
I've created a [branch](https://github.com/GlotPress/GlotPress-WP/tree/615-disable-api-by-default) that implements this for discussion.

**Comment by ocean90** [comment]
Long term, GlotPress should extend the default REST API in WordPress, see #338. Closing as wontfix.
