### ISSUE TITLE
Add 'fuzzy' to bulk actions and ability to mark translation as fuzzy

### ISSUE THREAD

**Issue by MarZab** [GlotPress/GlotPress#620]
My usecase is being able to filter out translations (for bad usage or from rogue translation editors) and mark them all as fuzzy so I get a list of translations to check and re-approve.

Another usecase is for translation editors who want to bring attention to a translation but without a good idea for a change at that point.

**Comment by tobifjellner** [comment]
Hmm. As a PTE, I'd like to be able to change temporarily to a mode where translations I add get marked as "waiting".

**Comment by MarZab** [comment]
Good point, for my needs /s/fuzzy/waiting would work as well.

**Comment by chantalcoolsma** [comment]
> As a PTE, I'd like to be able to change temporarily to a mode where translations I add get marked as "waiting".

This is already possible with an import. Can you explain a little bit more please?

**Comment by MarZab** [comment]
I don't think you can mark strings as waiting when you have not made a change?

**Comment by tobifjellner** [comment]
I'm mainly working on glotpress online. In projects, where I'm PTE, all my translations become green/approved immediately. In projects, where I'm not the PTE, my added translations become suggestions/yellow/waiting.
In some cases, say, when translating the readme for a new release, it would be good to have the opportunity to mark your translation as waiting, as a way to request more eyes to theese strings (even if you're a PTE or GTE).

**Comment by chantalcoolsma** [comment]
> I don't think you can mark strings as waiting when you have not made a change?

I don't see the need why you would. Please explain using an example why it would matter?

**Comment by chantalcoolsma** [comment]
@tobifjellner as a GTE I see this too. However I don't think it is really an issue. If a string need some review, we discuss it on Slack in the Dutch Polyglots team, before we translate it.

Any thoughts @ocean90?

**Comment by MarZab** [comment]
Let me reiterate my original usecase:

I have a translation set I re-delegated to another editor since the old one made a complete mess of things. There are 1300+ strings that are 30% bonkers approved by this person. The 2500 other ones are fine.

The new editor will need to make a complete review and the amount of these is just too much to handle at once, so the best way (in my mind) would be to mark all of the strings as fuzzy/waiting using the filter/bulk action.

I do not want to:
- check all the strings again by myself or give someone this task or duplicate effort, its hard to get validators as it is
- reject all the strings from the old validator since 70% of them are ok and sort of usable, thet just need to be checked

Again, I am not talking about single one-off bad translations that need review. I'm talking about managing large sets of translations and delegating work to other validators.

**Comment by chantalcoolsma** [comment]
@MarZab good point!

**Comment by toolstack** [comment]
This seems like a corner case brought on by having a bad translator more than something that will happen very often.

The bulk action menu isn't probably a very good way to handle this as it would be limited to the maximum number of entries per page, if the user had a few thousand string you might have to apply the bulk filter dozens (hundreds?) of times.

A better way would be to have a UI to handle marking all strings by a given users as fuzzy (or rejected/etc.).

Either way, I think it is enough of a corner case as to be plugin material in comparison to a core GlotPress feature.

**Comment by ocean90** [comment]
I always thought that `fuzzy` is reserved for translations done through any sort of a machine. But the gettext manual mentions this case too:

> Also, **the translator may decide herself to mark an entry as fuzzy for her own convenience**, when she wants to remember that the entry has to be later revisited.
>
> – https://www.gnu.org/software/gettext/manual/html_node/Fuzzy-Entries.html

**Comment by chantalcoolsma** [comment]
So 'fuzzy' could also mean 'needs review' or something like that. Other than 'awaiting review' as in 'waiting'.

**Comment by toolstack** [comment]
Since it looks like users should be able too set the status to fuzzy, I've created PR #624 to add support to both the individual rows and the bulk action menu.  Keyboard shortcuts included (Ctrl-~).
