### ISSUE TITLE
Android format: Strings with "xliff" tag not imported fine

### ISSUE THREAD

**Issue by ignaciogs** [GlotPress/GlotPress#628]
Example in android format:

<string name="test">My name is \"<xliff:g id="name" example="John">%s</xliff:g>\".</string>

is imported as:

My name is "".

**Comment by ocean90** [comment]
Hello @ignaciogs, thanks for the report.

Can you provide some details/docs about this tag? The Android format supports only strings in a format like https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/res/values/strings.xml is.

**Comment by ignaciogs** [comment]
Hi, This is the android documentation
https://developer.android.com/distribute/tools/localization-checklist.html
see the "Mark message parts that should not be translated" section please

**Comment by toolstack** [comment]
This is caused by the simplexml parser parsing the xliff:g tag during import and we then do not look for it.

I've created a PR that resolves it by encapsulating the tag inside of a CDATA structure and enabling simplexml's option to ignore CDATA tags.

**Comment by pdalfarr** [comment]
Confirming this issue:
<xliff:g id="mail_account" example="first.last@gmail.com">**%s**</xliff:g> is not taken into account and is **lost** :-(
(%s disappeared: when I download the translation, the whole "<xliff:g id="mail_account" example="first.last@gmail.com">**%s**</xliff:g>" is **not** in the file anymore

When will your fix be available?
(I installed GlotPress using standard WordPress plugin system, i.e., install plugin from within WordPress admin panel)

Thanks for this amazing work!

**Note: Some (humble) thoughts**

In the example I gave, please note that xliff:g xml node give translators a hint about the value of '%s'. This is useful to help translator to **understand the context** of the text to be translated. Displaying this info in UI (if not too difficult for you) would really be useful!

So, when encountering this:
"Google account <xliff:g id="mail_account" example="first.last@gmail.com">**%s**</xliff:g>selected"
It could be handled like this:
- in the left (source) translation panel:
   "Google account [%s](mail_account&example=first.last@gmail.com) selected" (now %s is a "link" or, at least is displayed in some other way)
   when link is hovered, user could see:
    - <xliff:g id="mail_account" example="first.last@gmail.com"> or something similar
- Right Panel:
   will keep on displaying as now, i.e.:
   "Google account %s selected"  (no changes)
   and just make a check (obvious) that %s is still in translated text (then replaced by original xliff node when exporting)

**Comment by toolstack** [comment]
@pdalfarr doing a hover is very complex and probably needs some thought put behind it to handle all types of formats that might have this kind of requirement.

However I have [updated the PR](https://github.com/GlotPress/GlotPress-WP/pull/636#issuecomment-279092881) to handle them better by using the comment area to let the translator know what should not be edited.

**Comment by pdalfarr** [comment]
Your solution with comment area is great ! Thanks
