### ISSUE TITLE
Remove *_salt/*_hash functions

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress#65]
The following functions are no longer needed:
- _gp_get_secret_key
- _gp_get_salt
- gp_salt
- gp_hash
- gp_generate_password

All from /gp-includes/misc.php

**Comment by ocean90** [comment]
Or should we move them to deprecated.php?

**Comment by toolstack** [comment]
Just delete, I'd remove depricated as we're changing so much anyway.  Other than the core app, only plugins would be using this code and we've completly changed plugins so the old standalone ones won't work with the plugin anyway.
