### ISSUE TITLE
GlotPress access - Option to prevent 'not logged in' users to browser projects and translations

### ISSUE THREAD

**Issue by pdalfarr** [GlotPress/GlotPress#654]
About GlotPress access, is it a way to prevent 'not logged in' users to see & browser project / translations etc?

When not logged in, I am able to see Gltopress content (data like projects, translations, etc).
I would like to forbid that, so, only logged in user can see projects, translation etc..

 - Users not logged in could then only see GlotPress home page and will be asked to log in.
 - Users not logged in will be 'redirected' to GlotPress home page if trying to access any Glotpress urls other than 'GlotPress' Home (projects, translation, search page, etc).

Is this functionality already available? Did I miss something? (I read https://glotpress.blog/the-manual/ but didn't find that)

Thanks for this amazing piece of software :-)

**Comment by toolstack** [comment]
The standard behaviour for GlotPress is to allow anyone to view projects/translations, there's no built in way to change that.

However you could use my [plugin](https://wordpress.org/plugins/gp-require-login) to force user logins.

**Comment by pdalfarr** [comment]
@toolstack  Excellent! I'll try :-)

**Comment by pdalfarr** [comment]
Your [GP Require Login](https://wordpress.org/plugins/gp-require-login/) WordPress plugin do the job: great!

Maybe it could be mentioned in GlotPress's manual as an optional feature?

Thanks.

**Comment by toolstack** [comment]
I don't think we'd add it to the admin manual directly, but there is a [plugin list](https://github.com/GlotPress/GlotPress-WP/wiki/3.-GlotPress-plugins) on the GitHub Wiki (which I haven't updated in a while so it's not there either :wink:).
