### ISSUE TITLE
Review `$_GET = gp_urldecode_deep( $_GET );`

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress#67]
The line exists in gp-settings.php https://github.com/deliciousbrains/GlotPress/blob/ee8353be2b124d4339c9cb1d06a03b081eb6d4ee/gp-settings.php#L22 and was introduced in https://glotpress.trac.wordpress.org/changeset/303.

Could this break other plugins/themes or WordPress? Is it still needed? Needs a little review.

**Comment by toolstack** [comment]
I took a look and it I didn't find anything that really depends on this being done globally.  I disabled it and did some testing and didn't find any issues.

However if we think there could be a requirement we could remove it from gp-settings.php and instead update gp_get() to do the work on a per key basis instead.

**Comment by toolstack** [comment]
Ok, I've taken a deeper (no pun intended :wink:) look at this and found there are only 5 places in the code that directly access $_GET:
1. gp_settings.php: where the `$_GET = gp_urldecode_deep( $_GET );` line is.
2. gp_includes/misc.php: where gp_get() is defined.
3. gp_includes/routes/locale.php: should have used gp_get() anyway.
4.  gp_includes/routes/login.php: which is being removed in PR #82.
5. t/lib/testcase.php: used to setup the environment for the tests.

Item 4 can be ignored until PR #82 is implemented.
Item 5 is valid and doesn't need to be changed.

I'll create a PR to take care of 1, 2 and 3.  I'll remove the call from gp_settings and move it to gp_get() (takes care of 1&2) then replace the call in locale with gp_get() (takes care of 3).
