### ISSUE TITLE
Replace gp_redirect() with wp_redirect()

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress#70]
WordPress: https://github.com/WordPress/WordPress/blob/4204afdd402533586cb54e5ca06e5b0d0e1fc365/wp-includes/pluggable.php#L1197-L1231

GlotPress: https://github.com/deliciousbrains/GlotPress/blob/ee8353be2b124d4339c9cb1d06a03b081eb6d4ee/gp-includes/misc.php#L109-L126

Actually the only difference are the filter names… `global $is_IIS;` doesn't exist in GP, see the note.

**Comment by toolstack** [comment]
Could there be a reason to keep it for the different filter names?  

I'm thinking of GP plugins that could filter GP redirects without having to process ALL WP redirects as well?

**Comment by ocean90** [comment]
We could do something like this:

```
add_filter( 'wp_redirect', function( $location, $status ) {
    return add_filter( 'gp_redirect', $location, $status );
}, 10, 2 );
```

**Comment by toolstack** [comment]
That would just call gp_redirect each time wp_redirect was called correct?  

No real benefit to that unless we only set it during the router or some other point that only executes when a glotpress page is being displaed.

**Comment by ocean90** [comment]
@toolstack "like this". ;)

The filter would only be registered in https://github.com/deliciousbrains/GlotPress/blob/wordpress-plugin-dbi/gp-includes/route.php#L119

**Comment by toolstack** [comment]
That would do the trick.

**Comment by A5hleyRich** [comment]
Not bothering with the filter, as per:

https://wordpress.slack.com/archives/glotpress/p1445520712000314
