### ISSUE TITLE
backpress_set_cookie() and backpress_gmt_strtotime()

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress#71]
`backpress_set_cookie()` and `backpress_gmt_strtotime()` are the only functions which are prefixed with `backpress_`, defined in gp-includes/misc.php: https://github.com/deliciousbrains/GlotPress/blob/d6d64318936885320a3e9412a3ce3c9ed28cd764/gp-includes/misc.php#L459-L484.

We should check if they can be replaced with WP function. If not, then we should prefix them with `gp_`.

**Comment by toolstack** [comment]
I took a quick look through the code and it looks like backpress_set_cookie() could be replaced with the equivalent WP function but I don't see an equivalent function in WP.

backpress_gmt_strtotime() needs to remain by the looks of it as it makes sure the time is in GMT before converting it to a timestamp.

Looks like we'll have to rename them.
