### ISSUE TITLE
Remove gp_limit_for_page()

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress#73]
`gp_limit_for_page()` in https://github.com/deliciousbrains/GlotPress/blob/d6d64318936885320a3e9412a3ce3c9ed28cd764/gp-includes/misc.php#L128-L137 looks dangerous and should be removed. It doesn't get used anymore.

Introduced in https://glotpress.trac.wordpress.org/changeset/78

**Comment by toolstack** [comment]
If it's not used it's just cruft :wink:
