### ISSUE TITLE
Trying to log out shows Are you sure? message

### ISSUE THREAD

**Issue by bjork** [GlotPress/GlotPress#75]
GP_Route_Login redirects to a URL that `wp_logout_url()` returns. That URL is HTML encoded, so query parameters, especially `_wpnonce`, will not get read right.

Nonces won't help, if they never get printed to a web page, so instead of using the logout route, the logout link should point directly to wp-login.php using the wp_logout_url() function. Or, if the route is deemed to be worth saving, the logout link should have a nonce in it and the final WordPress logout url should be manually constructed.

**Comment by ocean90** [comment]
Another idea is to replace the encoded ampersand in `logout()`:

```
$logout_url = wp_logout_url( gp_url( '/' ) );
$logout_url = str_replace( '&amp;', '&', $logout_url ); // wp_nonce_url() returns HTML escaped URLs
$this->redirect( $logout_url );
```

**Comment by bjork** [comment]
That will solve the immediate issue, but won't protect logout from CSRF.

**Comment by toolstack** [comment]
I don't see any reason to keep the logout route so directly pointing to the WP logout link seems reasonable.

If there was some reason to keep it, would it make sense to use html_entity_decode() instead of just the str_replace() to make sure we catch everything?
