### ISSUE TITLE
gp-settings.php shouldn't include function declarations

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress#85]
I think `gp-settings.php` should only define constants/globals, include/require files and register plugin (de)activation hooks.

I'd also like to see all `add_action()` and `add_filter()` calls to be added to [gp-includes/default-filters.php](https://github.com/deliciousbrains/GlotPress/blob/5360b4ff5ccfa01a4830455135f3423e9ccded6d/gp-includes/default-filters.php). (Related core ticket: [#30947](https://core.trac.wordpress.org/ticket/30947)

Thoughts? Objections?

**Comment by toolstack** [comment]
I was thinking along the same lines, in fact I'd go a step farther and say the (de)activation hooks should probably be in the main plugin file (glotpress.php).

**Comment by bradt** [comment]
:+1:
