### ISSUE TITLE
PHP 7 compatibility

### ISSUE THREAD

**Issue by bradt** [GlotPress/GlotPress#86]
I've added this to the 1.0 milestone for now, but it's up for debate. WordPress core will be supporting PHP 7 when it is released next month.

**Comment by ocean90** [comment]
:+1: would be nice to get #31 ready.

**Comment by bradt** [comment]
Yea, @gilbitron is on vacation this week too, so feel free to take over #32, or just scrap it and do your own thing.

**Comment by toolstack** [comment]
:+1: I'd say this is a good thing to have for 1.0, PHP 7 will be released by then and we'll have enough time to test with it.

**Comment by A5hleyRich** [comment]
I've started testing GlotPress on PHP 7 today using [HGV](https://github.com/wpengine/hgv). Everything seems to work fine so far, no fatal errors or notices triggered.

**Comment by ocean90** [comment]
Travis CI Build with PHP7 is passing: https://travis-ci.org/deliciousbrains/GlotPress/jobs/87684312
