### ISSUE TITLE
Backwards Compatibility

### ISSUE THREAD

**Issue by bradt** [GlotPress/GlotPress#9]
How much should we worry about backwards compatibility?

When it comes to plugins, I don't think we should worry at all. All GlotPress plugins will need to be converted to WordPress plugins anyways as per #7.

Themes might be a different story. I'm sure lots of people have heavily customized their GlotPress themes, so it would be nice to allow people to switch to the GlotPress plugin from a standalone install using their existing GlotPress theme. Would be great to hear from people who have a custom GlotPress theme...

**Comment by toolstack** [comment]
Backwards compatibility shouldn't be a major concern in my opinion.  GP has never had an official 1.0 release so everything is up for grabs.

**Comment by bradt** [comment]
The version number shouldn't be a factor here. There's people using GP in production environments and depending on it. If we can make it easier for them to adopt the plugin with little effort, we should do it.

**Comment by toolstack** [comment]
As long as it doesn't burden us with lots of hacks to support the old I agree, but anyone converting to the plugin version is likely going to be doing so very carefully to start with.  If there is something that has to be converted or changed from the old to the new it should be a one of script with instructions for the admin, not something that runs all the time as part of the plugin.

**Comment by bradt** [comment]
Discussed further here: https://wordpress.slack.com/archives/glotpress/p1443705526000940

**Comment by ocean90** [comment]
I've started a wiki page which mentions some of the breaking changes: https://github.com/deliciousbrains/GlotPress/wiki/1.1-Breaking-Changes
