### ISSUE TITLE
No UI to delete a project

### ISSUE THREAD

**Issue by toolstack** [GlotPress/GlotPress#92]
There's currently a route to delete projects that works but no UI to access it.  A UI should be added.

**Comment by ocean90** [comment]
>  that works

That's relative. :)

There shouldn't be any UI until we have figured out what "deleting a project" actually means to us. Like what should happen to sub projects, originals, translation sets, translations, and glossaries?

Related: https://glotpress.trac.wordpress.org/ticket/186

**Comment by toolstack** [comment]
Then we should probably yank the route as you can manually type in the URL and GlotPress will "delete" the project (whatever that currently means to the code).
