### ISSUE TITLE
Remove unused function gp_add_slash

### ISSUE THREAD

**Issue by bjork** [GlotPress/GlotPress#94]
`wp-includes/strings.php` contains these functions related to multibyte string handling:
- `gp_strtolower()`
- `gp_strlen()`
- `gp_stripos()`
- `gp_substr()`

All of which are wrappers for functions that exists in PHP 5.2 or lower with a fallback for older versions. Thus, these functions could be deleted after replacing their usage elsewhere in the plugin with direct access to native functions.

Additionally, `gp_add_slash()` is not used at all and has a WP equivalent in `trailingslashit()`.

**Comment by ocean90** [comment]
Sadly mbstring is a non-default extension, so it can be disabled.

**Comment by bjork** [comment]
Alright, that explains it.

Well, since `gp_add_slash()` is unused, this issue is not 100% inaccurate. Will rename the issue.
