### ISSUE TITLE
Improve i18n

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress#99]
Previously: #16 
- [ ] Placeholders aren't explained in a translator comments
- [x] The use of `_n()` is wrong in some cases, like `_n('One translation rejected.', '%d translations rejected.', $ok, 'glotpress' ), $ok );`
- [ ] Strings like `__( 'edit', 'glotpress' )` should get a context:  `_x( 'edit', 'glossary', 'glotpress' )`
- [x] `esc_attr( __( ) )` should be `esc_attr__( )`
- [x] `echo _x( )` should be `_ex( )`

Note: Each point can have its own PR.

**Comment by toolstack** [comment]
PR #101 cleans up _n().

**Comment by shield-9** [comment]
Some strings in [gp-templates/project-permissions.php](https://github.com/deliciousbrains/GlotPress/blob/wordpress-plugin-dbi/gp-templates/project-permissions.php#L20-L26) would be impossible to be translated into some languages. (For example, Japanese.)

**Comment by toolstack** [comment]
Could you provide an example of what can't be translated? 

Items like the slug, username, login id, etc. aren't translated as they shouldn't be.

**Comment by shield-9** [comment]
@toolstack: Japanese has quite different sentence structure. In this case, _word order_ is the problem. Here's an example:
- English: `user <a href="{user_nicename}">{user_login}</a> can {action} strings with locale {locale_slug} and slug {set_slug}`
- Japanese: `ユーザー <a href="{user_nicename}">{user_login}</a> はロケール {locale_slug} で、スラッグ {set_slug} の文字列を {action} できます`

**Comment by toolstack** [comment]
@shield-9 take a look at #188, would that work better?

**Comment by ramiy** [comment]
See also https://github.com/deliciousbrains/GlotPress/pull/198 

Merge similar strings with different variations and avoid using HTML `<code>` tags in translation strings.

**Comment by pedro-mendonca** [comment]
Hi @ocean90 

I have some suggestions to improve i18n.

- [x] Merge the following Priority labels (have [commit](https://github.com/GlotPress/GlotPress-WP/pull/813/commits/daa83f2ffdda7915c232592e5a7074ef72ed1874)):
 - `Priority of the original:`
-  `Priority:`


- [x] Move arrows outside of the following strings and merge similar (have [commit](https://github.com/GlotPress/GlotPress-WP/pull/813/commits/7cf19df1c12343291f3f86176c0a257fad77af8a)):
- `Project actions &darr;`
- `Project actions &uarr;`
- `Personal project options &darr;`
- `Personal project options &uarr;`

**Comment by pedro-mendonca** [comment]
Hi @ocean90,
Regarding the above item:
> * [ ] Strings like __( 'edit', 'glotpress' ) should get a context: _x( 'edit', 'glossary', 'glotpress' )

Did you mean the `__( '(edit)', 'glotpress' )` used for _Glossary_, _Project_ and _Translation set_?

There are also these two, that I believe you weren't refering to:
`__( 'Edit', 'glotpress' ),`
`__( 'Delete', 'glotpress' ),`

**Comment by pedro-mendonca** [comment]
I'll post here another I18n issue that occurs in many pages:
![imagem](https://user-images.githubusercontent.com/7371591/101173193-1861d580-363a-11eb-97a3-f3447078412e.png)

The action links aren't separated with a space.
This would be easily fixed as below:
Current code example:
`return gp_link_get( gp_url( gp_url_join( '/glossaries', $glossary->id, '-edit' ) ), $text, gp_attrs_add_class( $attrs, 'action edit' ) );`

Fix with prepend empty space on add custom text link:
`return gp_link_get( gp_url( gp_url_join( '/glossaries', $glossary->id, '-edit' ) ), ' ' . $text, gp_attrs_add_class( $attrs, 'action edit' ) );`

**Comment by pedro-mendonca** [comment]
A better alternative is prepend all `$text` on `gp_link_get()`:
```
return sprintf(
	'%1$s<a href="%2$s"%3$s>%4$s</a>%5$s',
	$before,
	esc_url( $url ),
	$attributes,
	' ' . $text,
	$after
);
```
